/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/group-call-monitor/wrangler.jsonc --include-runtime=false --env-interface=CallMonitorEnv workers/group-call-monitor/worker-configuration.d.ts` (hash: 2db685e93a649f848c541bc2b5822a0e)
interface __BaseEnv_CallMonitorEnv {
	DB: D1Database;
	OA_BOT_ID: "Ucc21cbcb817af4a3b91def3ab6e04c09";
	TEST_CHAT_ID: "Cf2b0d931f735b48b044c47d841a32fda";
	CHAT_SCOPE: "all";
	SEND_ENABLED: "true";
	CALL_MONITOR: DurableObjectNamespace<import("./index").GroupCallMonitor>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "GroupCallMonitor";
	}
	interface Env extends __BaseEnv_CallMonitorEnv {}
}
interface CallMonitorEnv extends __BaseEnv_CallMonitorEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OA_BOT_ID" | "TEST_CHAT_ID" | "CHAT_SCOPE" | "SEND_ENABLED">> {}
}
