-- 共通称号カタログ(300種類)のシード。scripts/gen-title-seed.mjs が生成。
--
-- 既存の title_master(グループ別称号)には一切触らない。こちらは
-- common_title_master として完全に別管理する。名前が同じ称号があっても
-- 自動統合しない(指示どおり)。
--
-- INSERT OR IGNORE なので、再実行しても件数は増えない。

INSERT OR IGNORE INTO common_title_category (id, name, kind, display_order) VALUES
  ('personality', '性格・雰囲気', 'free', 1),
  ('social', '人との関わり', 'free', 2),
  ('daily', '暮らし・時間', 'free', 3),
  ('relax', 'のんびり', 'free', 4),
  ('hobbies', '趣味・創作', 'free', 5),
  ('games', 'ゲーム・遊び', 'free', 6),
  ('music', '音楽', 'free', 7),
  ('culture', '映画・読書', 'free', 8),
  ('food', '食べ物・飲み物', 'free', 9),
  ('animals', '動物', 'free', 10),
  ('nature', '自然・季節', 'free', 11),
  ('style', '色・装い', 'free', 12),
  ('growth', 'レベル実績', 'earned', 13),
  ('othello_achievement', 'オセロ実績', 'earned', 14);

INSERT OR IGNORE INTO common_title_master
  (id, category, name, name_norm, display_order, unlock_type, unlock_value, unlock_label, rule_status)
VALUES
  ('free_personality_001', 'personality', 'ノーマル', 'ノーマル', 1, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_002', 'personality', 'マイペース', 'マイペース', 2, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_003', 'personality', '自然体', '自然体', 3, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_004', 'personality', '好奇心旺盛', '好奇心旺盛', 4, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_005', 'personality', '直感派', '直感派', 5, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_006', 'personality', '慎重派', '慎重派', 6, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_007', 'personality', 'こだわり派', 'こだわり派', 7, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_008', 'personality', '楽観派', '楽観派', 8, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_009', 'personality', '行動派', '行動派', 9, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_010', 'personality', '負けず嫌い', '負けず嫌い', 10, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_011', 'personality', 'おっとり', 'おっとり', 11, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_012', 'personality', 'さっぱり', 'さっぱり', 12, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_013', 'personality', 'おちゃめ', 'おちゃめ', 13, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_014', 'personality', '照れ屋', '照れ屋', 14, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_015', 'personality', '気まぐれ', '気まぐれ', 15, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_016', 'personality', '一途', '一途', 16, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_017', 'personality', '柔軟思考', '柔軟思考', 17, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_018', 'personality', '理屈も大事', '理屈も大事', 18, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_019', 'personality', 'ひらめき派', 'ひらめき派', 19, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_personality_020', 'personality', 'ひそかな情熱', 'ひそかな情熱', 20, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_001', 'social', '聞き上手', '聞き上手', 21, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_002', 'social', '話し好き', '話し好き', 22, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_003', 'social', 'ツッコミ役', 'ツッコミ役', 23, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_004', 'social', '気配り上手', '気配り上手', 24, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_005', 'social', '笑顔で参加', '笑顔で参加', 25, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_006', 'social', 'まずは見守り', 'まずは見守り', 26, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_007', 'social', '相談どうぞ', '相談どうぞ', 27, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_008', 'social', '応援したい', '応援したい', 28, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_009', 'social', '感謝を忘れず', '感謝を忘れず', 29, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_010', 'social', '人なつっこい', '人なつっこい', 30, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_011', 'social', 'ほどよい距離', 'ほどよい距離', 31, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_012', 'social', '初対面は静か', '初対面は静か', 32, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_013', 'social', '仲良くしたい', '仲良くしたい', 33, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_014', 'social', '輪をつなぐ', '輪をつなぐ', 34, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_015', 'social', 'ほめ上手', 'ほめ上手', 35, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_016', 'social', '誘われ待ち', '誘われ待ち', 36, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_017', 'social', '冗談好き', '冗談好き', 37, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_018', 'social', '約束は大事', '約束は大事', 38, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_019', 'social', '一緒に考える', '一緒に考える', 39, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_social_020', 'social', '少人数派', '少人数派', 40, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_001', 'daily', '夜型', '夜型', 41, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_002', 'daily', '朝型', '朝型', 42, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_003', 'daily', '早寝早起き', '早寝早起き', 43, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_004', 'daily', '朝はゆっくり', '朝はゆっくり', 44, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_005', 'daily', '夕方から元気', '夕方から元気', 45, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_006', 'daily', '週末待ち', '週末待ち', 46, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_007', 'daily', 'すきま時間', 'すきま時間', 47, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_008', 'daily', 'ただいま休憩', 'ただいま休憩', 48, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_009', 'daily', '準備は前日', '準備は前日', 49, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_010', 'daily', '予定はゆるめ', '予定はゆるめ', 50, 'free', NULL, '最初から選択可能', 'free_choice');

INSERT OR IGNORE INTO common_title_master
  (id, category, name, name_norm, display_order, unlock_type, unlock_value, unlock_label, rule_status)
VALUES
  ('free_daily_011', 'daily', '思い立ったら', '思い立ったら', 51, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_012', 'daily', '一日一歩', '一日一歩', 52, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_013', 'daily', '切り替え上手', '切り替え上手', 53, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_014', 'daily', '寄り道ぐせ', '寄り道ぐせ', 54, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_015', 'daily', '身軽な暮らし', '身軽な暮らし', 55, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_016', 'daily', '整理整頓派', '整理整頓派', 56, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_017', 'daily', '時間ぴったり', '時間ぴったり', 57, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_018', 'daily', '明日から本気', '明日から本気', 58, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_019', 'daily', '平日こつこつ', '平日こつこつ', 59, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_daily_020', 'daily', '帰宅で復活', '帰宅で復活', 60, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_001', 'relax', 'のんびり', 'のんびり', 61, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_002', 'relax', 'まったり', 'まったり', 62, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_003', 'relax', 'ぼちぼち', 'ぼちぼち', 63, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_004', 'relax', 'ひとやすみ', 'ひとやすみ', 64, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_005', 'relax', '深呼吸', '深呼吸', 65, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_006', 'relax', '脱力モード', '脱力モード', 66, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_007', 'relax', '無理しない', '無理しない', 67, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_008', 'relax', 'ほどほど主義', 'ほどほど主義', 68, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_009', 'relax', '休息優先', '休息優先', 69, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_010', 'relax', 'ごろごろ中', 'ごろごろ中', 70, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_011', 'relax', 'ひとり時間', 'ひとり時間', 71, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_012', 'relax', 'ひなたぼっこ', 'ひなたぼっこ', 72, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_013', 'relax', '何もしない日', '何もしない日', 73, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_014', 'relax', 'おふとん待機', 'おふとん待機', 74, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_015', 'relax', '静かに充電', '静かに充電', 75, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_016', 'relax', 'ぬくぬく', 'ぬくぬく', 76, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_017', 'relax', '心に余白', '心に余白', 77, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_018', 'relax', 'ご自愛中', 'ご自愛中', 78, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_019', 'relax', '小さな幸せ', '小さな幸せ', 79, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_relax_020', 'relax', '平穏第一', '平穏第一', 80, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_001', 'hobbies', 'お絵描き好き', 'お絵描き好き', 81, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_002', 'hobbies', 'カメラさんぽ', 'カメラさんぽ', 82, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_003', 'hobbies', '編み物好き', '編み物好き', 83, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_004', 'hobbies', '刺繍びより', '刺繍びより', 84, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_005', 'hobbies', '折り紙好き', '折り紙好き', 85, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_006', 'hobbies', 'プラモ好き', 'プラモ好き', 86, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_007', 'hobbies', '工作の時間', '工作の時間', 87, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_008', 'hobbies', '手帳を飾る人', '手帳を飾る人', 88, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_009', 'hobbies', '文房具好き', '文房具好き', 89, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_010', 'hobbies', 'シール集め', 'シール集め', 90, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_011', 'hobbies', 'アクセ作り好き', 'アクセ作り好き', 91, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_012', 'hobbies', '陶芸に夢中', '陶芸に夢中', 92, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_013', 'hobbies', 'レジン細工好き', 'レジン細工好き', 93, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_014', 'hobbies', 'ミニチュア好き', 'ミニチュア好き', 94, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_015', 'hobbies', '裁縫好き', '裁縫好き', 95, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_016', 'hobbies', 'DIY派', 'diy派', 96, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_017', 'hobbies', 'ネイル好き', 'ネイル好き', 97, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_018', 'hobbies', 'コスプレ好き', 'コスプレ好き', 98, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_019', 'hobbies', '消しゴムはんこ', '消しゴムはんこ', 99, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_hobbies_020', 'hobbies', '手書き文字好き', '手書き文字好き', 100, 'free', NULL, '最初から選択可能', 'free_choice');

INSERT OR IGNORE INTO common_title_master
  (id, category, name, name_norm, display_order, unlock_type, unlock_value, unlock_label, rule_status)
VALUES
  ('free_games_001', 'games', 'オセロ好き', 'オセロ好き', 101, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_002', 'games', 'パズル好き', 'パズル好き', 102, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_003', 'games', 'ボードゲーム派', 'ボードゲーム派', 103, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_004', 'games', 'カードゲーム派', 'カードゲーム派', 104, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_005', 'games', '協力プレイ派', '協力プレイ派', 105, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_006', 'games', '対戦も好き', '対戦も好き', 106, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_007', 'games', 'ソロでじっくり', 'ソロでじっくり', 107, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_008', 'games', 'のんびり攻略', 'のんびり攻略', 108, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_009', 'games', '謎解き好き', '謎解き好き', 109, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_010', 'games', 'リズムゲーム派', 'リズムゲーム派', 110, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_011', 'games', 'レースゲーム派', 'レースゲーム派', 111, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_012', 'games', '育成ゲーム派', '育成ゲーム派', 112, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_013', 'games', '箱庭ゲーム派', '箱庭ゲーム派', 113, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_014', 'games', '格闘ゲーム好き', '格闘ゲーム好き', 114, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_015', 'games', 'クイズ好き', 'クイズ好き', 115, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_016', 'games', 'すごろく好き', 'すごろく好き', 116, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_017', 'games', '将棋好き', '将棋好き', 117, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_018', 'games', '麻雀好き', '麻雀好き', 118, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_019', 'games', 'ミニゲーム好き', 'ミニゲーム好き', 119, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_games_020', 'games', 'ゲーム実況好き', 'ゲーム実況好き', 120, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_001', 'music', '音楽が相棒', '音楽が相棒', 121, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_002', 'music', '歌うのが好き', '歌うのが好き', 122, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_003', 'music', 'カラオケ好き', 'カラオケ好き', 123, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_004', 'music', '鼻歌まじり', '鼻歌まじり', 124, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_005', 'music', 'ライブに行きたい', 'ライブに行きたい', 125, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_006', 'music', '演奏してみたい', '演奏してみたい', 126, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_007', 'music', 'ロック好き', 'ロック好き', 127, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_008', 'music', 'ポップス好き', 'ポップス好き', 128, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_009', 'music', 'ジャズ気分', 'ジャズ気分', 129, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_010', 'music', 'クラシック好き', 'クラシック好き', 130, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_011', 'music', 'ヒップホップ好き', 'ヒップホップ好き', 131, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_012', 'music', 'ダンス音楽好き', 'ダンス音楽好き', 132, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_013', 'music', 'ゆったり聴く派', 'ゆったり聴く派', 133, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_014', 'music', '歌詞を味わう人', '歌詞を味わう人', 134, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_015', 'music', 'メロディー重視', 'メロディー重視', 135, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_016', 'music', '低音好き', '低音好き', 136, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_017', 'music', 'ピアノ好き', 'ピアノ好き', 137, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_018', 'music', 'ギターに夢中', 'ギターに夢中', 138, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_019', 'music', '選曲を楽しむ人', '選曲を楽しむ人', 139, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_music_020', 'music', '新曲チェック派', '新曲チェック派', 140, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_001', 'culture', '映画好き', '映画好き', 141, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_002', 'culture', '読書好き', '読書好き', 142, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_003', 'culture', '漫画好き', '漫画好き', 143, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_004', 'culture', 'アニメ好き', 'アニメ好き', 144, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_005', 'culture', '美術館好き', '美術館好き', 145, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_006', 'culture', '舞台を観たい', '舞台を観たい', 146, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_007', 'culture', '映画館派', '映画館派', 147, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_008', 'culture', 'おうち上映会', 'おうち上映会', 148, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_009', 'culture', '短編好き', '短編好き', 149, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_010', 'culture', '長編じっくり派', '長編じっくり派', 150, 'free', NULL, '最初から選択可能', 'free_choice');

INSERT OR IGNORE INTO common_title_master
  (id, category, name, name_norm, display_order, unlock_type, unlock_value, unlock_label, rule_status)
VALUES
  ('free_culture_011', 'culture', 'ミステリー好き', 'ミステリー好き', 151, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_012', 'culture', 'SF好き', 'sf好き', 152, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_013', 'culture', 'ファンタジー好き', 'ファンタジー好き', 153, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_014', 'culture', 'コメディ好き', 'コメディ好き', 154, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_015', 'culture', '時代劇好き', '時代劇好き', 155, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_016', 'culture', 'ドキュメンタリー派', 'ドキュメンタリー派', 156, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_017', 'culture', 'エッセイ好き', 'エッセイ好き', 157, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_018', 'culture', '詩を味わう人', '詩を味わう人', 158, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_019', 'culture', '絵本好き', '絵本好き', 159, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_culture_020', 'culture', '考察を楽しむ人', '考察を楽しむ人', 160, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_001', 'food', '甘党', '甘党', 161, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_002', 'food', 'おやつの時間', 'おやつの時間', 162, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_003', 'food', '和菓子派', '和菓子派', 163, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_004', 'food', '洋菓子派', '洋菓子派', 164, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_005', 'food', 'チョコびいき', 'チョコびいき', 165, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_006', 'food', 'アイス推し', 'アイス推し', 166, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_007', 'food', 'プリン推し', 'プリン推し', 167, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_008', 'food', '焼き菓子好き', '焼き菓子好き', 168, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_009', 'food', 'パン派', 'パン派', 169, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_010', 'food', 'ごはん派', 'ごはん派', 170, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_011', 'food', '麺好き', '麺好き', 171, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_012', 'food', 'おにぎり派', 'おにぎり派', 172, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_013', 'food', 'カレー気分', 'カレー気分', 173, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_014', 'food', 'もちもち派', 'もちもち派', 174, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_015', 'food', 'さくさく派', 'さくさく派', 175, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_016', 'food', 'こんがり派', 'こんがり派', 176, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_017', 'food', 'コーヒー派', 'コーヒー派', 177, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_018', 'food', '紅茶派', '紅茶派', 178, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_019', 'food', 'お茶の時間', 'お茶の時間', 179, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_food_020', 'food', 'ココア気分', 'ココア気分', 180, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_001', 'animals', 'ねこ派', 'ねこ派', 181, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_002', 'animals', 'いぬ派', 'いぬ派', 182, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_003', 'animals', 'うさぎ推し', 'うさぎ推し', 183, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_004', 'animals', 'ハムスター派', 'ハムスター派', 184, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_005', 'animals', '小鳥好き', '小鳥好き', 185, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_006', 'animals', '文鳥派', '文鳥派', 186, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_007', 'animals', 'インコ派', 'インコ派', 187, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_008', 'animals', 'ペンギン推し', 'ペンギン推し', 188, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_009', 'animals', 'パンダ推し', 'パンダ推し', 189, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_010', 'animals', 'しろくま派', 'しろくま派', 190, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_011', 'animals', 'カワウソ推し', 'カワウソ推し', 191, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_012', 'animals', 'カピバラ派', 'カピバラ派', 192, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_013', 'animals', 'きつね派', 'きつね派', 193, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_014', 'animals', 'たぬき派', 'たぬき派', 194, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_015', 'animals', 'ひつじ派', 'ひつじ派', 195, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_016', 'animals', 'イルカ好き', 'イルカ好き', 196, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_017', 'animals', 'くらげ派', 'くらげ派', 197, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_018', 'animals', '熱帯魚好き', '熱帯魚好き', 198, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_019', 'animals', 'もふもふ派', 'もふもふ派', 199, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_animals_020', 'animals', '肉球好き', '肉球好き', 200, 'free', NULL, '最初から選択可能', 'free_choice');

INSERT OR IGNORE INTO common_title_master
  (id, category, name, name_norm, display_order, unlock_type, unlock_value, unlock_label, rule_status)
VALUES
  ('free_nature_001', 'nature', '春びいき', '春びいき', 201, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_002', 'nature', '夏びいき', '夏びいき', 202, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_003', 'nature', '秋びいき', '秋びいき', 203, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_004', 'nature', '冬びいき', '冬びいき', 204, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_005', 'nature', '桜好き', '桜好き', 205, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_006', 'nature', '新緑好き', '新緑好き', 206, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_007', 'nature', '紅葉好き', '紅葉好き', 207, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_008', 'nature', '雪景色派', '雪景色派', 208, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_009', 'nature', '晴れの日派', '晴れの日派', 209, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_010', 'nature', '雨音好き', '雨音好き', 210, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_011', 'nature', '木漏れ日好き', '木漏れ日好き', 211, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_012', 'nature', '夕焼け派', '夕焼け派', 212, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_013', 'nature', '朝焼け派', '朝焼け派', 213, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_014', 'nature', '星空派', '星空派', 214, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_015', 'nature', '月夜好き', '月夜好き', 215, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_016', 'nature', '海派', '海派', 216, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_017', 'nature', '山派', '山派', 217, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_018', 'nature', '森派', '森派', 218, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_019', 'nature', '花のある暮らし', '花のある暮らし', 219, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_nature_020', 'nature', 'そよ風びいき', 'そよ風びいき', 220, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_001', 'style', 'モノトーン派', 'モノトーン派', 221, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_002', 'style', 'パステル派', 'パステル派', 222, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_003', 'style', 'くすみカラー派', 'くすみカラー派', 223, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_004', 'style', 'ビビッド派', 'ビビッド派', 224, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_005', 'style', '青推し', '青推し', 225, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_006', 'style', '緑推し', '緑推し', 226, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_007', 'style', '赤推し', '赤推し', 227, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_008', 'style', '黄色推し', '黄色推し', 228, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_009', 'style', 'ピンク派', 'ピンク派', 229, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_010', 'style', 'むらさき派', 'むらさき派', 230, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_011', 'style', 'ナチュラル派', 'ナチュラル派', 231, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_012', 'style', 'シンプル派', 'シンプル派', 232, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_013', 'style', 'レトロ好み', 'レトロ好み', 233, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_014', 'style', 'ヴィンテージ派', 'ヴィンテージ派', 234, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_015', 'style', 'カジュアル派', 'カジュアル派', 235, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_016', 'style', 'きれいめ派', 'きれいめ派', 236, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_017', 'style', 'ゆったり派', 'ゆったり派', 237, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_018', 'style', 'ふわふわ派', 'ふわふわ派', 238, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_019', 'style', 'きらきら派', 'きらきら派', 239, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('free_style_020', 'style', '柄もの派', '柄もの派', 240, 'free', NULL, '最初から選択可能', 'free_choice'),
  ('earned_growth_001', 'growth', 'はじめの一歩', 'はじめの一歩', 241, 'level', 5, 'Lv. 5で解放', 'proposal_requires_review'),
  ('earned_growth_002', 'growth', 'ルーキー', 'ルーキー', 242, 'level', 10, 'Lv. 10で解放', 'proposal_requires_review'),
  ('earned_growth_003', 'growth', '成長中', '成長中', 243, 'level', 15, 'Lv. 15で解放', 'proposal_requires_review'),
  ('earned_growth_004', 'growth', 'コツコツ派', 'コツコツ派', 244, 'level', 20, 'Lv. 20で解放', 'proposal_requires_review'),
  ('earned_growth_005', 'growth', 'ひとつ上へ', 'ひとつ上へ', 245, 'level', 25, 'Lv. 25で解放', 'proposal_requires_review'),
  ('earned_growth_006', 'growth', 'ベテラン', 'ベテラン', 246, 'level', 30, 'Lv. 30で解放', 'proposal_requires_review'),
  ('earned_growth_007', 'growth', '積み重ね上手', '積み重ね上手', 247, 'level', 35, 'Lv. 35で解放', 'proposal_requires_review'),
  ('earned_growth_008', 'growth', '確かな足どり', '確かな足どり', 248, 'level', 40, 'Lv. 40で解放', 'proposal_requires_review'),
  ('earned_growth_009', 'growth', '自分のペース', '自分のペース', 249, 'level', 45, 'Lv. 45で解放', 'proposal_requires_review'),
  ('earned_growth_010', 'growth', '節目の達成者', '節目の達成者', 250, 'level', 50, 'Lv. 50で解放', 'proposal_requires_review');

INSERT OR IGNORE INTO common_title_master
  (id, category, name, name_norm, display_order, unlock_type, unlock_value, unlock_label, rule_status)
VALUES
  ('earned_growth_011', 'growth', '伸び盛り', '伸び盛り', 251, 'level', 55, 'Lv. 55で解放', 'proposal_requires_review'),
  ('earned_growth_012', 'growth', '継続のかたち', '継続のかたち', 252, 'level', 60, 'Lv. 60で解放', 'proposal_requires_review'),
  ('earned_growth_013', 'growth', '日々の積み重ね', '日々の積み重ね', 253, 'level', 65, 'Lv. 65で解放', 'proposal_requires_review'),
  ('earned_growth_014', 'growth', '努力の結晶', '努力の結晶', 254, 'level', 70, 'Lv. 70で解放', 'proposal_requires_review'),
  ('earned_growth_015', 'growth', '次のステージ', '次のステージ', 255, 'level', 75, 'Lv. 75で解放', 'proposal_requires_review'),
  ('earned_growth_016', 'growth', '安定した歩み', '安定した歩み', 256, 'level', 80, 'Lv. 80で解放', 'proposal_requires_review'),
  ('earned_growth_017', 'growth', '着実な成長', '着実な成長', 257, 'level', 85, 'Lv. 85で解放', 'proposal_requires_review'),
  ('earned_growth_018', 'growth', '大台目前', '大台目前', 258, 'level', 90, 'Lv. 90で解放', 'proposal_requires_review'),
  ('earned_growth_019', 'growth', 'もうひと伸び', 'もうひと伸び', 259, 'level', 95, 'Lv. 95で解放', 'proposal_requires_review'),
  ('earned_growth_020', 'growth', '百の足あと', '百の足あと', 260, 'level', 100, 'Lv. 100で解放', 'proposal_requires_review'),
  ('earned_growth_021', 'growth', '新しい景色', '新しい景色', 261, 'level', 105, 'Lv. 105で解放', 'proposal_requires_review'),
  ('earned_growth_022', 'growth', '続けるちから', '続けるちから', 262, 'level', 110, 'Lv. 110で解放', 'proposal_requires_review'),
  ('earned_growth_023', 'growth', '一歩先へ', '一歩先へ', 263, 'level', 115, 'Lv. 115で解放', 'proposal_requires_review'),
  ('earned_growth_024', 'growth', '深まる経験', '深まる経験', 264, 'level', 120, 'Lv. 120で解放', 'proposal_requires_review'),
  ('earned_growth_025', 'growth', '自分越え', '自分越え', 265, 'level', 125, 'Lv. 125で解放', 'proposal_requires_review'),
  ('earned_growth_026', 'growth', '揺るがぬ歩み', '揺るがぬ歩み', 266, 'level', 130, 'Lv. 130で解放', 'proposal_requires_review'),
  ('earned_growth_027', 'growth', '磨かれる個性', '磨かれる個性', 267, 'level', 135, 'Lv. 135で解放', 'proposal_requires_review'),
  ('earned_growth_028', 'growth', '経験豊富', '経験豊富', 268, 'level', 140, 'Lv. 140で解放', 'proposal_requires_review'),
  ('earned_growth_029', 'growth', '積み重なる日々', '積み重なる日々', 269, 'level', 145, 'Lv. 145で解放', 'proposal_requires_review'),
  ('earned_growth_030', 'growth', '百五十の節目', '百五十の節目', 270, 'level', 150, 'Lv. 150で解放', 'proposal_requires_review'),
  ('earned_growth_031', 'growth', 'まだまだ成長期', 'まだまだ成長期', 271, 'level', 155, 'Lv. 155で解放', 'proposal_requires_review'),
  ('earned_growth_032', 'growth', '進化の途中', '進化の途中', 272, 'level', 160, 'Lv. 160で解放', 'proposal_requires_review'),
  ('earned_growth_033', 'growth', '長く楽しむ人', '長く楽しむ人', 273, 'level', 165, 'Lv. 165で解放', 'proposal_requires_review'),
  ('earned_growth_034', 'growth', '継続の達人', '継続の達人', 274, 'level', 170, 'Lv. 170で解放', 'proposal_requires_review'),
  ('earned_growth_035', 'growth', '遠くまで来た', '遠くまで来た', 275, 'level', 175, 'Lv. 175で解放', 'proposal_requires_review'),
  ('earned_growth_036', 'growth', '新たな一歩', '新たな一歩', 276, 'level', 180, 'Lv. 180で解放', 'proposal_requires_review'),
  ('earned_growth_037', 'growth', 'さらなる高み', 'さらなる高み', 277, 'level', 185, 'Lv. 185で解放', 'proposal_requires_review'),
  ('earned_growth_038', 'growth', '歩みを止めない', '歩みを止めない', 278, 'level', 190, 'Lv. 190で解放', 'proposal_requires_review'),
  ('earned_growth_039', 'growth', '次の大台へ', '次の大台へ', 279, 'level', 195, 'Lv. 195で解放', 'proposal_requires_review'),
  ('earned_growth_040', 'growth', '二百の足あと', '二百の足あと', 280, 'level', 200, 'Lv. 200で解放', 'proposal_requires_review'),
  ('earned_othello_001', 'othello_achievement', '初めての白星', '初めての白星', 281, 'othello_wins', 1, 'オセロ1勝で解放', 'proposal_requires_review'),
  ('earned_othello_002', 'othello_achievement', '一手の手応え', '一手の手応え', 282, 'othello_wins', 3, 'オセロ3勝で解放', 'proposal_requires_review'),
  ('earned_othello_003', 'othello_achievement', '盤面ウォッチャー', '盤面ウォッチャー', 283, 'othello_wins', 5, 'オセロ5勝で解放', 'proposal_requires_review'),
  ('earned_othello_004', 'othello_achievement', 'オセロ通', 'オセロ通', 284, 'othello_wins', 10, 'オセロ10勝で解放', 'proposal_requires_review'),
  ('earned_othello_005', 'othello_achievement', 'ひっくり返し上手', 'ひっくり返し上手', 285, 'othello_wins', 15, 'オセロ15勝で解放', 'proposal_requires_review'),
  ('earned_othello_006', 'othello_achievement', '読みが冴える', '読みが冴える', 286, 'othello_wins', 20, 'オセロ20勝で解放', 'proposal_requires_review'),
  ('earned_othello_007', 'othello_achievement', '白黒の駆け引き', '白黒の駆け引き', 287, 'othello_wins', 30, 'オセロ30勝で解放', 'proposal_requires_review'),
  ('earned_othello_008', 'othello_achievement', '一手を大切に', '一手を大切に', 288, 'othello_wins', 40, 'オセロ40勝で解放', 'proposal_requires_review'),
  ('earned_othello_009', 'othello_achievement', '五十の白星', '五十の白星', 289, 'othello_wins', 50, 'オセロ50勝で解放', 'proposal_requires_review'),
  ('earned_othello_010', 'othello_achievement', '先を読む人', '先を読む人', 290, 'othello_wins', 75, 'オセロ75勝で解放', 'proposal_requires_review'),
  ('earned_othello_011', 'othello_achievement', '百勝の記録', '百勝の記録', 291, 'othello_wins', 100, 'オセロ100勝で解放', 'proposal_requires_review'),
  ('earned_othello_012', 'othello_achievement', '盤上の集中力', '盤上の集中力', 292, 'othello_wins', 125, 'オセロ125勝で解放', 'proposal_requires_review'),
  ('earned_othello_013', 'othello_achievement', '白星コレクター', '白星コレクター', 293, 'othello_wins', 150, 'オセロ150勝で解放', 'proposal_requires_review'),
  ('earned_othello_014', 'othello_achievement', '二百勝の足あと', '二百勝の足あと', 294, 'othello_wins', 200, 'オセロ200勝で解放', 'proposal_requires_review'),
  ('earned_othello_015', 'othello_achievement', '勝負勘あり', '勝負勘あり', 295, 'othello_wins', 250, 'オセロ250勝で解放', 'proposal_requires_review'),
  ('earned_othello_016', 'othello_achievement', '三百勝の記録', '三百勝の記録', 296, 'othello_wins', 300, 'オセロ300勝で解放', 'proposal_requires_review'),
  ('earned_othello_017', 'othello_achievement', '読みを磨いた証', '読みを磨いた証', 297, 'othello_wins', 400, 'オセロ400勝で解放', 'proposal_requires_review'),
  ('earned_othello_018', 'othello_achievement', '五百勝の節目', '五百勝の節目', 298, 'othello_wins', 500, 'オセロ500勝で解放', 'proposal_requires_review'),
  ('earned_othello_019', 'othello_achievement', '白黒を極める', '白黒を極める', 299, 'othello_wins', 750, 'オセロ750勝で解放', 'proposal_requires_review'),
  ('earned_othello_020', 'othello_achievement', '千勝の記録', '千勝の記録', 300, 'othello_wins', 1000, 'オセロ1000勝で解放', 'proposal_requires_review');
