// Generated by scripts/import-dressup-assets.py from the approved catalogs.
export interface Cosmetic {
  id: string
  name: string
  kind: 'costume' | 'background'
  category: string
  imagePath: string
}
export const DEFAULT_COSTUME: Cosmetic = {"id": "C000", "name": "いつものもち", "kind": "costume", "category": "初期", "imagePath": "/static/dressup/C000.png"}
export const DEFAULT_BACKGROUND: Cosmetic = {"id": "BG000", "name": "そらいろ", "kind": "background", "category": "初期", "imagePath": "/static/dressup/BG000.png"}
export const COSMETICS: readonly Cosmetic[] = [
  {
    "id": "C001",
    "name": "おやすみもち",
    "kind": "costume",
    "category": "おうち時間",
    "imagePath": "/static/dressup/C001.png"
  },
  {
    "id": "C002",
    "name": "おふろもち",
    "kind": "costume",
    "category": "おうち時間",
    "imagePath": "/static/dressup/C002.png"
  },
  {
    "id": "C003",
    "name": "はみがきもち",
    "kind": "costume",
    "category": "おうち時間",
    "imagePath": "/static/dressup/C003.png"
  },
  {
    "id": "C004",
    "name": "おそうじもち",
    "kind": "costume",
    "category": "おうち時間",
    "imagePath": "/static/dressup/C004.png"
  },
  {
    "id": "C005",
    "name": "おせんたくもち",
    "kind": "costume",
    "category": "おうち時間",
    "imagePath": "/static/dressup/C005.png"
  },
  {
    "id": "C006",
    "name": "えほんもち",
    "kind": "costume",
    "category": "おうち時間",
    "imagePath": "/static/dressup/C006.png"
  },
  {
    "id": "C007",
    "name": "あみものもち",
    "kind": "costume",
    "category": "おうち時間",
    "imagePath": "/static/dressup/C007.png"
  },
  {
    "id": "C008",
    "name": "こたつもち",
    "kind": "costume",
    "category": "おうち時間",
    "imagePath": "/static/dressup/C008.png"
  },
  {
    "id": "C009",
    "name": "くつろぎもち",
    "kind": "costume",
    "category": "おうち時間",
    "imagePath": "/static/dressup/C009.png"
  },
  {
    "id": "C010",
    "name": "かみひこうきもち",
    "kind": "costume",
    "category": "おうち時間",
    "imagePath": "/static/dressup/C010.png"
  },
  {
    "id": "C011",
    "name": "シネマもち",
    "kind": "costume",
    "category": "おうち時間",
    "imagePath": "/static/dressup/C011.png"
  },
  {
    "id": "C012",
    "name": "ゲームもち",
    "kind": "costume",
    "category": "おうち時間",
    "imagePath": "/static/dressup/C012.png"
  },
  {
    "id": "C013",
    "name": "プリンもち",
    "kind": "costume",
    "category": "カフェとお菓子",
    "imagePath": "/static/dressup/C013.png"
  },
  {
    "id": "C014",
    "name": "ケーキもち",
    "kind": "costume",
    "category": "カフェとお菓子",
    "imagePath": "/static/dressup/C014.png"
  },
  {
    "id": "C015",
    "name": "ドーナツもち",
    "kind": "costume",
    "category": "カフェとお菓子",
    "imagePath": "/static/dressup/C015.png"
  },
  {
    "id": "C016",
    "name": "パンケーキもち",
    "kind": "costume",
    "category": "カフェとお菓子",
    "imagePath": "/static/dressup/C016.png"
  },
  {
    "id": "C017",
    "name": "クロワッサンもち",
    "kind": "costume",
    "category": "カフェとお菓子",
    "imagePath": "/static/dressup/C017.png"
  },
  {
    "id": "C018",
    "name": "クリームソーダもち",
    "kind": "costume",
    "category": "カフェとお菓子",
    "imagePath": "/static/dressup/C018.png"
  },
  {
    "id": "C019",
    "name": "アイスもち",
    "kind": "costume",
    "category": "カフェとお菓子",
    "imagePath": "/static/dressup/C019.png"
  },
  {
    "id": "C020",
    "name": "クッキーもち",
    "kind": "costume",
    "category": "カフェとお菓子",
    "imagePath": "/static/dressup/C020.png"
  },
  {
    "id": "C021",
    "name": "マカロンもち",
    "kind": "costume",
    "category": "カフェとお菓子",
    "imagePath": "/static/dressup/C021.png"
  },
  {
    "id": "C022",
    "name": "チョコもち",
    "kind": "costume",
    "category": "カフェとお菓子",
    "imagePath": "/static/dressup/C022.png"
  },
  {
    "id": "C023",
    "name": "たい焼きもち",
    "kind": "costume",
    "category": "カフェとお菓子",
    "imagePath": "/static/dressup/C023.png"
  },
  {
    "id": "C024",
    "name": "ポットもち",
    "kind": "costume",
    "category": "カフェとお菓子",
    "imagePath": "/static/dressup/C024.png"
  },
  {
    "id": "C025",
    "name": "シェフもち",
    "kind": "costume",
    "category": "おしごと",
    "imagePath": "/static/dressup/C025.png"
  },
  {
    "id": "C026",
    "name": "パンやもち",
    "kind": "costume",
    "category": "おしごと",
    "imagePath": "/static/dressup/C026.png"
  },
  {
    "id": "C027",
    "name": "おいしゃもち",
    "kind": "costume",
    "category": "おしごと",
    "imagePath": "/static/dressup/C027.png"
  },
  {
    "id": "C028",
    "name": "しょうぼうもち",
    "kind": "costume",
    "category": "おしごと",
    "imagePath": "/static/dressup/C028.png"
  },
  {
    "id": "C029",
    "name": "けいさつもち",
    "kind": "costume",
    "category": "おしごと",
    "imagePath": "/static/dressup/C029.png"
  },
  {
    "id": "C030",
    "name": "パイロットもち",
    "kind": "costume",
    "category": "おしごと",
    "imagePath": "/static/dressup/C030.png"
  },
  {
    "id": "C031",
    "name": "こうじもち",
    "kind": "costume",
    "category": "おしごと",
    "imagePath": "/static/dressup/C031.png"
  },
  {
    "id": "C032",
    "name": "ゆうびんもち",
    "kind": "costume",
    "category": "おしごと",
    "imagePath": "/static/dressup/C032.png"
  },
  {
    "id": "C033",
    "name": "はなやもち",
    "kind": "costume",
    "category": "おしごと",
    "imagePath": "/static/dressup/C033.png"
  },
  {
    "id": "C034",
    "name": "たんていもち",
    "kind": "costume",
    "category": "おしごと",
    "imagePath": "/static/dressup/C034.png"
  },
  {
    "id": "C035",
    "name": "えかきもち",
    "kind": "costume",
    "category": "おしごと",
    "imagePath": "/static/dressup/C035.png"
  },
  {
    "id": "C036",
    "name": "のうかもち",
    "kind": "costume",
    "category": "おしごと",
    "imagePath": "/static/dressup/C036.png"
  },
  {
    "id": "C037",
    "name": "うさぎもち",
    "kind": "costume",
    "category": "どうぶつ",
    "imagePath": "/static/dressup/C037.png"
  },
  {
    "id": "C038",
    "name": "ねこもち",
    "kind": "costume",
    "category": "どうぶつ",
    "imagePath": "/static/dressup/C038.png"
  },
  {
    "id": "C039",
    "name": "いぬもち",
    "kind": "costume",
    "category": "どうぶつ",
    "imagePath": "/static/dressup/C039.png"
  },
  {
    "id": "C040",
    "name": "くまもち",
    "kind": "costume",
    "category": "どうぶつ",
    "imagePath": "/static/dressup/C040.png"
  },
  {
    "id": "C041",
    "name": "パンダもち",
    "kind": "costume",
    "category": "どうぶつ",
    "imagePath": "/static/dressup/C041.png"
  },
  {
    "id": "C042",
    "name": "キツネもち",
    "kind": "costume",
    "category": "どうぶつ",
    "imagePath": "/static/dressup/C042.png"
  },
  {
    "id": "C043",
    "name": "ハリネズミもち",
    "kind": "costume",
    "category": "どうぶつ",
    "imagePath": "/static/dressup/C043.png"
  },
  {
    "id": "C044",
    "name": "ひつじもち",
    "kind": "costume",
    "category": "どうぶつ",
    "imagePath": "/static/dressup/C044.png"
  },
  {
    "id": "C045",
    "name": "ペンギンもち",
    "kind": "costume",
    "category": "どうぶつ",
    "imagePath": "/static/dressup/C045.png"
  },
  {
    "id": "C046",
    "name": "ひよこもち",
    "kind": "costume",
    "category": "どうぶつ",
    "imagePath": "/static/dressup/C046.png"
  },
  {
    "id": "C047",
    "name": "あざらしもち",
    "kind": "costume",
    "category": "どうぶつ",
    "imagePath": "/static/dressup/C047.png"
  },
  {
    "id": "C048",
    "name": "リスもち",
    "kind": "costume",
    "category": "どうぶつ",
    "imagePath": "/static/dressup/C048.png"
  },
  {
    "id": "C049",
    "name": "魔法使いもち",
    "kind": "costume",
    "category": "ファンタジー",
    "imagePath": "/static/dressup/C049.png"
  },
  {
    "id": "C050",
    "name": "王さまもち",
    "kind": "costume",
    "category": "ファンタジー",
    "imagePath": "/static/dressup/C050.png"
  },
  {
    "id": "C051",
    "name": "おひめさまもち",
    "kind": "costume",
    "category": "ファンタジー",
    "imagePath": "/static/dressup/C051.png"
  },
  {
    "id": "C052",
    "name": "ナイトもち",
    "kind": "costume",
    "category": "ファンタジー",
    "imagePath": "/static/dressup/C052.png"
  },
  {
    "id": "C053",
    "name": "ドラゴンもち",
    "kind": "costume",
    "category": "ファンタジー",
    "imagePath": "/static/dressup/C053.png"
  },
  {
    "id": "C054",
    "name": "ようせいもち",
    "kind": "costume",
    "category": "ファンタジー",
    "imagePath": "/static/dressup/C054.png"
  },
  {
    "id": "C055",
    "name": "にんぎょもち",
    "kind": "costume",
    "category": "ファンタジー",
    "imagePath": "/static/dressup/C055.png"
  },
  {
    "id": "C056",
    "name": "ユニコーンもち",
    "kind": "costume",
    "category": "ファンタジー",
    "imagePath": "/static/dressup/C056.png"
  },
  {
    "id": "C057",
    "name": "てんしもち",
    "kind": "costume",
    "category": "ファンタジー",
    "imagePath": "/static/dressup/C057.png"
  },
  {
    "id": "C058",
    "name": "こあくまもち",
    "kind": "costume",
    "category": "ファンタジー",
    "imagePath": "/static/dressup/C058.png"
  },
  {
    "id": "C059",
    "name": "かいぞくもち",
    "kind": "costume",
    "category": "ファンタジー",
    "imagePath": "/static/dressup/C059.png"
  },
  {
    "id": "C060",
    "name": "マジシャンもち",
    "kind": "costume",
    "category": "ファンタジー",
    "imagePath": "/static/dressup/C060.png"
  },
  {
    "id": "C061",
    "name": "忍者もち",
    "kind": "costume",
    "category": "和のくらし",
    "imagePath": "/static/dressup/C061.png"
  },
  {
    "id": "C062",
    "name": "着物もち",
    "kind": "costume",
    "category": "和のくらし",
    "imagePath": "/static/dressup/C062.png"
  },
  {
    "id": "C063",
    "name": "和傘もち",
    "kind": "costume",
    "category": "和のくらし",
    "imagePath": "/static/dressup/C063.png"
  },
  {
    "id": "C064",
    "name": "茶道もち",
    "kind": "costume",
    "category": "和のくらし",
    "imagePath": "/static/dressup/C064.png"
  },
  {
    "id": "C065",
    "name": "書道もち",
    "kind": "costume",
    "category": "和のくらし",
    "imagePath": "/static/dressup/C065.png"
  },
  {
    "id": "C066",
    "name": "落語もち",
    "kind": "costume",
    "category": "和のくらし",
    "imagePath": "/static/dressup/C066.png"
  },
  {
    "id": "C067",
    "name": "折り紙もち",
    "kind": "costume",
    "category": "和のくらし",
    "imagePath": "/static/dressup/C067.png"
  },
  {
    "id": "C068",
    "name": "風呂敷もち",
    "kind": "costume",
    "category": "和のくらし",
    "imagePath": "/static/dressup/C068.png"
  },
  {
    "id": "C069",
    "name": "相撲もち",
    "kind": "costume",
    "category": "和のくらし",
    "imagePath": "/static/dressup/C069.png"
  },
  {
    "id": "C070",
    "name": "獅子舞もち",
    "kind": "costume",
    "category": "和のくらし",
    "imagePath": "/static/dressup/C070.png"
  },
  {
    "id": "C071",
    "name": "手まりもち",
    "kind": "costume",
    "category": "和のくらし",
    "imagePath": "/static/dressup/C071.png"
  },
  {
    "id": "C072",
    "name": "こけしもち",
    "kind": "costume",
    "category": "和のくらし",
    "imagePath": "/static/dressup/C072.png"
  },
  {
    "id": "C073",
    "name": "お正月もち",
    "kind": "costume",
    "category": "季節とイベント",
    "imagePath": "/static/dressup/C073.png"
  },
  {
    "id": "C074",
    "name": "節分もち",
    "kind": "costume",
    "category": "季節とイベント",
    "imagePath": "/static/dressup/C074.png"
  },
  {
    "id": "C075",
    "name": "ひな祭りもち",
    "kind": "costume",
    "category": "季節とイベント",
    "imagePath": "/static/dressup/C075.png"
  },
  {
    "id": "C076",
    "name": "桜もち",
    "kind": "costume",
    "category": "季節とイベント",
    "imagePath": "/static/dressup/C076.png"
  },
  {
    "id": "C077",
    "name": "こいのぼりもち",
    "kind": "costume",
    "category": "季節とイベント",
    "imagePath": "/static/dressup/C077.png"
  },
  {
    "id": "C078",
    "name": "あじさいもち",
    "kind": "costume",
    "category": "季節とイベント",
    "imagePath": "/static/dressup/C078.png"
  },
  {
    "id": "C079",
    "name": "七夕もち",
    "kind": "costume",
    "category": "季節とイベント",
    "imagePath": "/static/dressup/C079.png"
  },
  {
    "id": "C080",
    "name": "花火もち",
    "kind": "costume",
    "category": "季節とイベント",
    "imagePath": "/static/dressup/C080.png"
  },
  {
    "id": "C081",
    "name": "月見もち",
    "kind": "costume",
    "category": "季節とイベント",
    "imagePath": "/static/dressup/C081.png"
  },
  {
    "id": "C082",
    "name": "ハロウィンもち",
    "kind": "costume",
    "category": "季節とイベント",
    "imagePath": "/static/dressup/C082.png"
  },
  {
    "id": "C083",
    "name": "クリスマスもち",
    "kind": "costume",
    "category": "季節とイベント",
    "imagePath": "/static/dressup/C083.png"
  },
  {
    "id": "C084",
    "name": "誕生日もち",
    "kind": "costume",
    "category": "季節とイベント",
    "imagePath": "/static/dressup/C084.png"
  },
  {
    "id": "C085",
    "name": "探検もち",
    "kind": "costume",
    "category": "旅とアウトドア",
    "imagePath": "/static/dressup/C085.png"
  },
  {
    "id": "C086",
    "name": "登山もち",
    "kind": "costume",
    "category": "旅とアウトドア",
    "imagePath": "/static/dressup/C086.png"
  },
  {
    "id": "C087",
    "name": "キャンプもち",
    "kind": "costume",
    "category": "旅とアウトドア",
    "imagePath": "/static/dressup/C087.png"
  },
  {
    "id": "C088",
    "name": "釣りもち",
    "kind": "costume",
    "category": "旅とアウトドア",
    "imagePath": "/static/dressup/C088.png"
  },
  {
    "id": "C089",
    "name": "サーフィンもち",
    "kind": "costume",
    "category": "旅とアウトドア",
    "imagePath": "/static/dressup/C089.png"
  },
  {
    "id": "C090",
    "name": "ダイビングもち",
    "kind": "costume",
    "category": "旅とアウトドア",
    "imagePath": "/static/dressup/C090.png"
  },
  {
    "id": "C091",
    "name": "スキーもち",
    "kind": "costume",
    "category": "旅とアウトドア",
    "imagePath": "/static/dressup/C091.png"
  },
  {
    "id": "C092",
    "name": "熱気球もち",
    "kind": "costume",
    "category": "旅とアウトドア",
    "imagePath": "/static/dressup/C092.png"
  },
  {
    "id": "C093",
    "name": "自転車もち",
    "kind": "costume",
    "category": "旅とアウトドア",
    "imagePath": "/static/dressup/C093.png"
  },
  {
    "id": "C094",
    "name": "カヌーもち",
    "kind": "costume",
    "category": "旅とアウトドア",
    "imagePath": "/static/dressup/C094.png"
  },
  {
    "id": "C095",
    "name": "世界旅行もち",
    "kind": "costume",
    "category": "旅とアウトドア",
    "imagePath": "/static/dressup/C095.png"
  },
  {
    "id": "C096",
    "name": "鉄道旅もち",
    "kind": "costume",
    "category": "旅とアウトドア",
    "imagePath": "/static/dressup/C096.png"
  },
  {
    "id": "C097",
    "name": "ピアノもち",
    "kind": "costume",
    "category": "音楽とステージ",
    "imagePath": "/static/dressup/C097.png"
  },
  {
    "id": "C098",
    "name": "ギターもち",
    "kind": "costume",
    "category": "音楽とステージ",
    "imagePath": "/static/dressup/C098.png"
  },
  {
    "id": "C099",
    "name": "ドラムもち",
    "kind": "costume",
    "category": "音楽とステージ",
    "imagePath": "/static/dressup/C099.png"
  },
  {
    "id": "C100",
    "name": "バイオリンもち",
    "kind": "costume",
    "category": "音楽とステージ",
    "imagePath": "/static/dressup/C100.png"
  },
  {
    "id": "C101",
    "name": "サックスもち",
    "kind": "costume",
    "category": "音楽とステージ",
    "imagePath": "/static/dressup/C101.png"
  },
  {
    "id": "C102",
    "name": "トランペットもち",
    "kind": "costume",
    "category": "音楽とステージ",
    "imagePath": "/static/dressup/C102.png"
  },
  {
    "id": "C103",
    "name": "ハープもち",
    "kind": "costume",
    "category": "音楽とステージ",
    "imagePath": "/static/dressup/C103.png"
  },
  {
    "id": "C104",
    "name": "アコーディオンもち",
    "kind": "costume",
    "category": "音楽とステージ",
    "imagePath": "/static/dressup/C104.png"
  },
  {
    "id": "C105",
    "name": "ディージェイもち",
    "kind": "costume",
    "category": "音楽とステージ",
    "imagePath": "/static/dressup/C105.png"
  },
  {
    "id": "C106",
    "name": "バレエもち",
    "kind": "costume",
    "category": "音楽とステージ",
    "imagePath": "/static/dressup/C106.png"
  },
  {
    "id": "C107",
    "name": "オペラもち",
    "kind": "costume",
    "category": "音楽とステージ",
    "imagePath": "/static/dressup/C107.png"
  },
  {
    "id": "C108",
    "name": "指揮者もち",
    "kind": "costume",
    "category": "音楽とステージ",
    "imagePath": "/static/dressup/C108.png"
  },
  {
    "id": "C109",
    "name": "宇宙飛行士もち",
    "kind": "costume",
    "category": "星空とふしぎ",
    "imagePath": "/static/dressup/C109.png"
  },
  {
    "id": "C110",
    "name": "三日月もち",
    "kind": "costume",
    "category": "星空とふしぎ",
    "imagePath": "/static/dressup/C110.png"
  },
  {
    "id": "C111",
    "name": "土星もち",
    "kind": "costume",
    "category": "星空とふしぎ",
    "imagePath": "/static/dressup/C111.png"
  },
  {
    "id": "C112",
    "name": "流れ星もち",
    "kind": "costume",
    "category": "星空とふしぎ",
    "imagePath": "/static/dressup/C112.png"
  },
  {
    "id": "C113",
    "name": "雲もち",
    "kind": "costume",
    "category": "星空とふしぎ",
    "imagePath": "/static/dressup/C113.png"
  },
  {
    "id": "C114",
    "name": "虹もち",
    "kind": "costume",
    "category": "星空とふしぎ",
    "imagePath": "/static/dressup/C114.png"
  },
  {
    "id": "C115",
    "name": "雷もち",
    "kind": "costume",
    "category": "星空とふしぎ",
    "imagePath": "/static/dressup/C115.png"
  },
  {
    "id": "C116",
    "name": "雪結晶もち",
    "kind": "costume",
    "category": "星空とふしぎ",
    "imagePath": "/static/dressup/C116.png"
  },
  {
    "id": "C117",
    "name": "オーロラもち",
    "kind": "costume",
    "category": "星空とふしぎ",
    "imagePath": "/static/dressup/C117.png"
  },
  {
    "id": "C118",
    "name": "水晶もち",
    "kind": "costume",
    "category": "星空とふしぎ",
    "imagePath": "/static/dressup/C118.png"
  },
  {
    "id": "C119",
    "name": "太陽もち",
    "kind": "costume",
    "category": "星空とふしぎ",
    "imagePath": "/static/dressup/C119.png"
  },
  {
    "id": "C120",
    "name": "星座もち",
    "kind": "costume",
    "category": "星空とふしぎ",
    "imagePath": "/static/dressup/C120.png"
  },
  {
    "id": "BG001",
    "name": "月と雲",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG001.png"
  },
  {
    "id": "BG002",
    "name": "朝のふわ雲",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG002.png"
  },
  {
    "id": "BG003",
    "name": "星降る寝室",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG003.png"
  },
  {
    "id": "BG004",
    "name": "魔法の図書館",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG004.png"
  },
  {
    "id": "BG005",
    "name": "王宮のテラス",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG005.png"
  },
  {
    "id": "BG006",
    "name": "妖精の森",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG006.png"
  },
  {
    "id": "BG007",
    "name": "月夜の屋根",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG007.png"
  },
  {
    "id": "BG008",
    "name": "桜の庭",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG008.png"
  },
  {
    "id": "BG009",
    "name": "和室と縁側",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG009.png"
  },
  {
    "id": "BG010",
    "name": "お菓子カフェ",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG010.png"
  },
  {
    "id": "BG011",
    "name": "苺とクリーム",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG011.png"
  },
  {
    "id": "BG012",
    "name": "焼きたてベーカリー",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG012.png"
  },
  {
    "id": "BG013",
    "name": "花咲く草原",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG013.png"
  },
  {
    "id": "BG014",
    "name": "木漏れ日の森",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG014.png"
  },
  {
    "id": "BG015",
    "name": "氷の海",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG015.png"
  },
  {
    "id": "BG016",
    "name": "街角の朝",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG016.png"
  },
  {
    "id": "BG017",
    "name": "ひだまりアトリエ",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG017.png"
  },
  {
    "id": "BG018",
    "name": "畑と風車",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG018.png"
  },
  {
    "id": "BG019",
    "name": "夕暮れキャンプ",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG019.png"
  },
  {
    "id": "BG020",
    "name": "南の海",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG020.png"
  },
  {
    "id": "BG021",
    "name": "空の旅",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG021.png"
  },
  {
    "id": "BG022",
    "name": "音楽ホール",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG022.png"
  },
  {
    "id": "BG023",
    "name": "きらめくステージ",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG023.png"
  },
  {
    "id": "BG024",
    "name": "レコードラウンジ",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG024.png"
  },
  {
    "id": "BG025",
    "name": "宇宙と地球",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG025.png"
  },
  {
    "id": "BG026",
    "name": "銀河と惑星",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG026.png"
  },
  {
    "id": "BG027",
    "name": "水晶の洞窟",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG027.png"
  },
  {
    "id": "BG028",
    "name": "花火の夜",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG028.png"
  },
  {
    "id": "BG029",
    "name": "雪のクリスマス",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG029.png"
  },
  {
    "id": "BG030",
    "name": "かぼちゃの館",
    "kind": "background",
    "category": "背景",
    "imagePath": "/static/dressup/BG030.png"
  }
]

const byId = new Map<string, Cosmetic>(
  [DEFAULT_COSTUME, DEFAULT_BACKGROUND, ...COSMETICS].map(item => [item.id, item]),
)
export function getCosmetic(id: string): Cosmetic | undefined {
  return byId.get(id)
}
