import { Hono } from 'hono'
import { serveStatic } from 'hono/cloudflare-workers'
import {
  replyMessage,
  getProfile,
  getGroupSummary,
  verifySignature,
  peekBroadcasts,
  markBroadcastsDelivered,
  type LineEnv,
  type LineMessage,
} from './lib/line'
import { handleUnsend } from './features/unsend'
import { cacheGroupMessage, touchGroupMember, ensureGroupMetadata, markGroupLeft, getGroupMessage } from './features/groupTracking'
import { buildWelcomeMessages } from './features/welcome'
import { registerBirthday, unregisterBirthday, checkAndQueueBirthdays } from './features/birthday'
// 運勢機能は廃止したため features/fortune.ts の import は無い。
// 個人ステータス(レベル/EXP/ポイント)・着せ替え・共通称号。
// 既存のグループ別称号(features/titles.ts)とは別系統の独立モジュール。
import { addExpForMessage } from './features/profile/core'
import { handleProfileText, handleProfilePostback } from './features/profile'
import { renderPersonalRankingPage, renderPublicStatusPage } from './features/profile/page'
// ヘルプメニュー(横スワイプのカルーセル + 案内画面)。
// 実装済みFlexは作り直さず、既存の出力へ渡すだけの薄い層。
import { handleMenuText, handleMenuPostback } from './features/menu'
import { checkAndQueueWeeklyRanking } from './features/ranking'
import { saveQuote, buildQuoteImageMessage } from './features/quote'
import { parseQuoteParams, describeParams, isPureParamString, FONT_LABELS } from './lib/quoteParams'
import { addTagToGroup, listGroupTags, removeTagFromGroup } from './features/tags'
import { setWelcomeSetting, clearWelcomeMessage } from './features/welcome'
import { equipTitle, getEquippedTitle, listUserTitles } from './features/titles'
import { startGame as startOthello, joinGame as joinOthello, endGame as endOthello, applyMove as applyOthelloMove, buildOthelloMessage, checkAndQueueOthelloTimeout, getOthelloRecord } from './features/othello'
import { getLatestAnnouncementMessages, checkAndQueueAnnouncements } from './features/announcements'
import {
  listThreads,
  listAllThreadIds,
  getThread,
  incrementThreadViews,
  likeThread,
  createThread,
  listChatMessages,
  postChatMessage,
  listChatMessagesAfter,
  chatMessageToJson,
  listComments,
  postComment,
  isRateLimited,
  touchRateLimit,
  getStats,
  saveContactMessage,
  listGalleryImages,
  deleteGalleryImage,
  renderThreadsListPage,
  renderThreadDetailPage,
  renderNewThreadPage,
  renderChatPage,
  renderGuidePage,
  renderGalleryPage,
  renderGalleryAdminLoginPage,
  renderErrorPage,
  renderRssFeed,
  CATEGORIES,
  SORT_OPTIONS,
  SITE_URL,
} from './features/bbs'
import { isAdminRequest, createSessionToken, buildSessionCookie, buildLogoutCookie, isAdminConfigured } from './features/galleryAdmin'
// グループ発言数ランキング(追加機能)。既存の週間個人ランキング
// (features/ranking.ts)とは別モジュールで、そちらには一切触れていない。
import {
  getGroupRanking,
  getGroupDetail,
  recordHourlyActivity,
  buildGroupRankingReply,
  type RankingPeriod,
  type SizeFilter,
} from './features/groupRanking'
import { renderRankingPage, renderRankingRulesPage } from './features/rankingPage'
// チェス(グループ対局)。既存のオセロ・他機能には一切関与しない独立モジュール。
import {
  handleChessText,
  handleChessPostback,
  onBotLeftGroup,
  onMemberLeftGroup,
  debugBuildCard,
} from './features/chess'
import { markEventProcessed } from './features/chess/store'

type Bindings = LineEnv

const app = new Hono<{ Bindings: Bindings }>()

app.use('/static/*', serveStatic({ root: './public' }))

// ─── Health check ───
app.get('/', (c) => c.text('HappaMochi Bot is running'))

// ─── Quote card image delivery ───
// Public, unauthenticated, plain-HTTPS GET endpoint that LINE's servers
// fetch directly when rendering an imageMessage (originalContentUrl /
// previewImageUrl). Serves the PNG bytes generated by generateQuoteCardPng
// and stored in quote_images.image_data (see features/quote.ts).
app.get('/quote-image/:id', async (c) => {
  const id = c.req.param('id')
  const row = await c.env.DB.prepare(`SELECT image_data FROM quote_images WHERE id = ?`)
    .bind(id)
    .first<{ image_data: ArrayBuffer }>()
  if (!row) return c.notFound()
  // D1's local (workerd/miniflare) emulation sometimes returns a BLOB column
  // as a plain JS Array of byte values instead of an ArrayBuffer. Passing
  // that array straight into `new Response()` gets it silently stringified
  // (BodyInit coercion calls String()/Array.prototype.join on it), which is
  // exactly the "137,80,78,71,..." decimal-CSV corruption bug. Normalize to
  // a real ArrayBuffer regardless of which shape D1 handed back.
  const raw = row.image_data as unknown
  const bytes = Array.isArray(raw) ? Uint8Array.from(raw as number[]) : new Uint8Array(raw as ArrayBuffer)
  return new Response(bytes, {
    headers: {
      'Content-Type': 'image/png',
      'Cache-Control': 'public, max-age=31536000, immutable',
    },
  })
})

// ─── グループ発言数ランキング ───
// LINE Botが集計した group_activities を集計源にした公開ページ。
// 読み取り専用で、Bot本体(webhook・コマンド処理)には一切関与しない。
// 集計に失敗した場合も 500 にせず、ページ内でエラー表示に切り替える。
// 個人ランキング。既存の /ranking(グループ発言数)とは別物なので
// パスを分けている。既存の集計方法は変更していない。
app.get('/ranking/personal', async (c) => {
  const page = Math.max(1, parseInt(c.req.query('page') || '1', 10) || 1)
  const html = await renderPersonalRankingPage(c.env, SITE_URL, page)
  return c.html(html)
})

// 公開ステータス。URLには public_id しか使わない(LINEのユーザーIDは
// 公開しない)。会話本文・グループ情報・誕生日は載せない。
app.get('/u/:publicId', async (c) => {
  const publicId = c.req.param('publicId').slice(0, 40)
  const { html, found } = await renderPublicStatusPage(c.env, SITE_URL, publicId)
  return c.html(html, found ? 200 : 404)
})

app.get('/ranking', async (c) => {
  const rawPeriod = c.req.query('period')
  const period: RankingPeriod =
    rawPeriod === 'today' || rawPeriod === 'month' ? rawPeriod : 'week'
  const rawSize = c.req.query('size')
  const size: SizeFilter =
    rawSize === 'small' || rawSize === 'medium' || rawSize === 'large' ? rawSize : 'all'
  const q = (c.req.query('q') || '').slice(0, 60)
  const page = Math.max(1, parseInt(c.req.query('page') || '1', 10) || 1)
  const groupId = c.req.query('group') || null

  const result = await getGroupRanking(c.env, { period, size, q, page })
  const detail = groupId ? await getGroupDetail(c.env, groupId, period) : null

  const generatedAt = new Date(Date.now() + 9 * 60 * 60 * 1000)
    .toISOString()
    .replace('T', ' ')
    .slice(0, 16)

  return c.html(
    renderRankingPage({ result, detail, period, size, q, generatedAt: `${generatedAt} JST` })
  )
})

app.get('/ranking/rules', (c) => c.html(renderRankingRulesPage()))

// ─── 名言カードギャラリー ───
// 「めいく」コマンドで生成された名言カード(quote_images)を一覧表示する
// 公開ページ。画像本体は上の /quote-image/:id を<img src>としてそのまま
// 使うだけで、新しい画像配信経路は追加しない。LINE Bot側のコマンド処理
// (index.tsx内のmeイクcommand handler / features/quote.ts)には一切触れない。
app.get('/gallery', async (c) => {
  const page = Math.max(1, parseInt(c.req.query('page') || '1', 10) || 1)
  const result = await listGalleryImages(c.env, page)
  const admin = await isAdminRequest(c.env, c.req.header('Cookie'))
  return c.html(renderGalleryPage(result, admin))
})

// ─── ギャラリー管理者ログイン/ログアウト/削除 ───
// LINE Bot本体(webhook, quote.ts, imageGen.ts)には一切関与しない、
// /gallery/admin* 専用の独立した認証・削除フロー。パスワードは
// Cloudflare のシークレット GALLERY_ADMIN_PASSWORD にのみ保存される。
app.get('/gallery/admin', async (c) => {
  const admin = await isAdminRequest(c.env, c.req.header('Cookie'))
  if (admin) return c.redirect('/gallery')
  if (!isAdminConfigured(c.env)) {
    return c.html(renderGalleryAdminLoginPage('管理者ログインは現在設定されていません。'), 503)
  }
  return c.html(renderGalleryAdminLoginPage())
})

app.post('/gallery/admin', async (c) => {
  const key = await clientKeyFor(c, 'gallery-admin-login')
  if (await isRateLimited(c.env, key)) {
    return c.html(renderGalleryAdminLoginPage('試行間隔が短すぎます。しばらく待ってから再度お試しください。'), 429)
  }
  await touchRateLimit(c.env, key)

  const body = await c.req.parseBody()
  const password = String(body.password ?? '')
  const token = await createSessionToken(c.env, password)
  if (!token) {
    return c.html(renderGalleryAdminLoginPage('パスワードが正しくありません。'), 401)
  }
  c.header('Set-Cookie', buildSessionCookie(token))
  return c.redirect('/gallery')
})

app.post('/gallery/admin/logout', async (c) => {
  c.header('Set-Cookie', buildLogoutCookie())
  return c.redirect('/gallery')
})

app.post('/gallery/admin/delete/:id', async (c) => {
  const admin = await isAdminRequest(c.env, c.req.header('Cookie'))
  if (!admin) return c.json({ error: 'unauthorized' }, 401)
  const id = c.req.param('id')
  const deleted = await deleteGalleryImage(c.env, id)
  if (!deleted) return c.json({ error: 'not found' }, 404)
  return c.json({ ok: true })
})

// ─── LINEグループ募集掲示板 (BBS) + オープンチャット ───
// Public, unauthenticated GET/POST website reading from (and preserving)
// the historical `threads` / `chat_messages` tables — see features/bbs.ts.
// This is a real website, NOT a LINE command; no Reply/Push API involved.

// 簡易レート制限用のクライアントキー(IPアドレスをそのまま保存しない = ハッシュ化)
async function clientKeyFor(c: { req: { header: (k: string) => string | undefined } }, scope: string): Promise<string> {
  const ip = c.req.header('CF-Connecting-IP') || c.req.header('x-forwarded-for') || 'unknown'
  const raw = `${scope}:${ip}`
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(raw))
  return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, '0')).join('')
}

app.get('/bbs', async (c) => {
  const category = c.req.query('category') || null
  const validCategory = category && CATEGORIES.some((x) => x.value === category) ? category : null
  const sortParam = c.req.query('sort') || 'new'
  const sort = SORT_OPTIONS.some((s) => s.value === sortParam) ? sortParam : 'new'
  const q = (c.req.query('q') || '').slice(0, 100)
  const page = Math.max(1, parseInt(c.req.query('page') || '1', 10) || 1)

  const [result, stats] = await Promise.all([
    listThreads(c.env, { category: validCategory, sort, q, page }),
    getStats(c.env),
  ])
  return c.html(renderThreadsListPage({ result, activeCategory: validCategory, sort, q, stats }))
})

app.get('/bbs/feed.xml', async (c) => {
  const { threads } = await listThreads(c.env, { sort: 'new', page: 1 })
  return c.text(renderRssFeed(threads), 200, { 'Content-Type': 'application/rss+xml; charset=utf-8' })
})

app.get('/bbs/new', (c) => {
  const category = c.req.query('category') || null
  return c.html(renderNewThreadPage(category))
})

app.post('/bbs/new', async (c) => {
  const key = await clientKeyFor(c, 'new-thread')
  if (await isRateLimited(c.env, key)) {
    return c.html(renderNewThreadPage(null, '投稿間隔が短すぎます。しばらく待ってから再度お試しください。'), 429)
  }

  const body = await c.req.parseBody()
  const category = String(body.category ?? '').trim()
  const title = String(body.title ?? '').trim()
  const content = String(body.content ?? '').trim()
  const author = String(body.author ?? '').trim()

  if (!CATEGORIES.some((x) => x.value === category) || !title || !content || !author) {
    return c.html(renderNewThreadPage(category || null, '入力内容を確認してください。'), 400)
  }

  const id = await createThread(c.env, { category, title, content, author })
  await touchRateLimit(c.env, key)
  return c.redirect(`/bbs/${encodeURIComponent(id)}`)
})

app.get('/bbs/chat', async (c) => {
  const messages = await listChatMessages(c.env)
  return c.html(renderChatPage(messages))
})

app.post('/bbs/chat', async (c) => {
  const key = await clientKeyFor(c, 'chat')
  if (await isRateLimited(c.env, key)) {
    const messages = await listChatMessages(c.env)
    return c.html(renderChatPage(messages), 429)
  }

  const body = await c.req.parseBody()
  const content = String(body.content ?? '').trim()
  const author = String(body.author ?? '').trim()
  if (content && author) {
    await postChatMessage(c.env, content, author)
    await touchRateLimit(c.env, key)
  }
  return c.redirect('/bbs/chat')
})

// 疑似リアルタイム用ポーリングAPI: 指定した created_at より新しいメッセージのみ返す。
// JavaScriptが有効なブラウザから3秒おきに呼ばれる。JSONのみ返し、HTMLは含まない。
app.get('/bbs/chat/messages', async (c) => {
  const after = c.req.query('after') || new Date(0).toISOString()
  const messages = await listChatMessagesAfter(c.env, after)
  return c.json({ messages: messages.map(chatMessageToJson) })
})

// Ajax投稿API: フォームのsubmitをpreventDefaultしてこちらへfetchする。
// 通常の /bbs/chat (フルページPOST) はJavaScript無効時のフォールバックとして残す。
app.post('/bbs/chat/messages', async (c) => {
  const key = await clientKeyFor(c, 'chat')
  if (await isRateLimited(c.env, key)) {
    return c.json({ error: '投稿間隔が短すぎます。少し待ってから再度お試しください。' }, 429)
  }

  const body = await c.req.parseBody()
  const content = String(body.content ?? '').trim()
  const author = String(body.author ?? '').trim()
  if (!content || !author) {
    return c.json({ error: '入力内容を確認してください。' }, 400)
  }

  const message = await postChatMessage(c.env, content, author)
  await touchRateLimit(c.env, key)
  return c.json({ message: chatMessageToJson(message) })
})

// 利用ガイドページ(はじめ方/利用ルール/安全のために/よくある質問/お問い合わせ)。
// お問い合わせフォームは実際にD1へ保存する(フェイクの「受け付けました」表示は禁止)。
// 注意: '/bbs/:id' より前に定義しないと 'guide' がスレッドIDとして誤認識されるため、
// 動的ルートより先に固定パスのガイドルートを登録する。
app.get('/bbs/guide', (c) => {
  return c.html(renderGuidePage())
})

app.post('/bbs/guide/contact', async (c) => {
  const key = await clientKeyFor(c, 'contact')
  const isFetch = c.req.header('X-Requested-With') === 'fetch'
  if (await isRateLimited(c.env, key)) {
    const msg = '送信間隔が短すぎます。しばらく待ってから再度お試しください。'
    if (isFetch) return c.json({ error: msg }, 429)
    return c.html(renderGuidePage({ error: msg }), 429)
  }

  const body = await c.req.parseBody()
  const content = String(body.content ?? '').trim()
  if (!content) {
    const msg = '内容を入力してください。'
    if (isFetch) return c.json({ error: msg }, 400)
    return c.html(renderGuidePage({ error: msg }), 400)
  }

  await saveContactMessage(c.env, content)
  await touchRateLimit(c.env, key)

  if (isFetch) return c.json({ ok: true })
  return c.html(renderGuidePage({ sent: true }))
})

app.get('/bbs/:id', async (c) => {
  const id = c.req.param('id')
  const thread = await getThread(c.env, id)
  if (!thread) return c.html(renderErrorPage(404, 'お探しの投稿は見つかりませんでした'), 404)
  await incrementThreadViews(c.env, id)
  const comments = await listComments(c.env, id)
  return c.html(renderThreadDetailPage(thread, comments))
})

app.post('/bbs/:id/like', async (c) => {
  const id = c.req.param('id')
  const likes = await likeThread(c.env, id)
  if (likes === null) return c.html(renderErrorPage(404, 'お探しの投稿は見つかりませんでした'), 404)
  return c.redirect(`/bbs/${encodeURIComponent(id)}`)
})

app.post('/bbs/:id/comment', async (c) => {
  const id = c.req.param('id')
  const thread = await getThread(c.env, id)
  if (!thread) return c.html(renderErrorPage(404, 'お探しの投稿は見つかりませんでした'), 404)

  const key = await clientKeyFor(c, 'comment')
  if (await isRateLimited(c.env, key)) {
    const comments = await listComments(c.env, id)
    return c.html(renderThreadDetailPage(thread, comments), 429)
  }

  const body = await c.req.parseBody()
  const author = String(body.author ?? '').trim()
  const content = String(body.content ?? '').trim()
  if (author && content) {
    await postComment(c.env, id, author, content)
    await touchRateLimit(c.env, key)
  }
  return c.redirect(`/bbs/${encodeURIComponent(id)}#comments-heading`)
})

// ─── SEO: robots.txt / sitemap.xml ───
app.get('/robots.txt', (c) => {
  return c.text(
    `User-agent: *\nAllow: /\nSitemap: ${SITE_URL}/sitemap.xml\n`,
    200,
    { 'Content-Type': 'text/plain; charset=utf-8' }
  )
})

app.get('/sitemap.xml', async (c) => {
  const threadRows = await listAllThreadIds(c.env)
  const staticUrls = ['/bbs', '/bbs/new', '/bbs/chat', '/bbs/guide', '/gallery', '/ranking', '/ranking/rules']
  const urls = [
    ...staticUrls.map((path) => `<url><loc>${SITE_URL}${path}</loc><changefreq>hourly</changefreq></url>`),
    ...threadRows.map(
      (t) => `<url><loc>${SITE_URL}/bbs/${t.id}</loc><lastmod>${new Date(t.created_at).toISOString()}</lastmod><changefreq>weekly</changefreq></url>`
    ),
  ].join('\n')
  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>`
  return c.text(xml, 200, { 'Content-Type': 'application/xml; charset=utf-8' })
})

// ─── Debug: simulate a text command WITHOUT touching LINE ───
// LINEに実際のメッセージを送らず、Botのコマンドロジックが「何を返そうとしているか」
// だけをJSONで確認できるエンドポイント。テスト用のreplyToken/署名は不要。
// 本番用途ではなく、動作確認専用(データベースへの書き込みは実際に発生する点に注意)。
// ─── チェスのテスト用: 対局状態の読み取り/初期化 ───
// 自動テスト(scripts/chess-test.mjs)から使う。読み取りと、
// chess_games テーブル内のテスト用グループ(接頭辞 Cchess_test_)に
// 限定した書き込みのみ。他のテーブル・本番グループには触れない。
app.post('/debug/chess', async (c) => {
  const body = (await c.req.json().catch(() => ({}))) as {
    op?: string
    groupId?: string
    id?: string
    set?: Record<string, string | number | null>
    kind?: string
    from?: string
    to?: string
  }
  const TEST_PREFIX = 'Cchess_test_'

  if (body.op === 'get') {
    const row = await c.env.DB.prepare(
      `SELECT * FROM chess_games WHERE group_id = ? ORDER BY created_at DESC LIMIT 1`
    )
      .bind(body.groupId ?? '')
      .first()
    return c.json({ game: row ?? null })
  }

  if (body.op === 'byId') {
    const row = await c.env.DB.prepare(`SELECT * FROM chess_games WHERE id = ?`)
      .bind(body.id ?? '')
      .first()
    return c.json({ game: row ?? null })
  }

  if (body.op === 'list') {
    const { results } = await c.env.DB.prepare(
      `SELECT * FROM chess_games WHERE group_id = ? ORDER BY created_at`
    )
      .bind(body.groupId ?? '')
      .all()
    return c.json({ games: results ?? [] })
  }

  // 指定グループの現在の状態から、LINEへ実際に送るのとまったく同じ関数で
  // Flexカードを生成して返す。サンプル出力・サイズ検証に使う。
  if (body.op === 'flex') {
    const row = await c.env.DB.prepare(
      `SELECT * FROM chess_games WHERE group_id = ? ORDER BY created_at DESC LIMIT 1`
    )
      .bind(body.groupId ?? '')
      .first()
    if (!row) return c.json({ error: 'no game' }, 404)
    const baseUrl = new URL(c.req.url).origin
    const kind = (body.kind ?? 'board') as 'board' | 'result' | 'recruit' | 'promotion'
    const msg = debugBuildCard(kind, row as any, baseUrl, {
      from: body.from,
      to: body.to,
    })
    return c.json({ message: msg })
  }

  // 以下はテスト用グループにのみ許可する
  const gid = body.groupId ?? ''
  if (!gid.startsWith(TEST_PREFIX)) return c.json({ error: 'test groups only' }, 403)

  if (body.op === 'reset') {
    await c.env.DB.prepare(`DELETE FROM chess_games WHERE group_id LIKE ?`)
      .bind(`${gid}%`)
      .run()
    return c.json({ ok: true })
  }

  if (body.op === 'patch' && body.id && body.set) {
    // 局面を直接差し替えて特殊ケース(昇格・メイト等)を作るためのもの
    const allowed = [
      'start_fen', 'current_fen', 'moves_json', 'turn', 'status',
      'expires_at', 'pending_from', 'pending_to', 'pending_token',
      'sel_square', 'sel_token', 'result', 'result_reason', 'version',
    ]
    const keys = Object.keys(body.set).filter((k) => allowed.includes(k))
    if (keys.length === 0) return c.json({ error: 'no allowed keys' }, 400)
    const sets = keys.map((k) => `${k} = ?`).join(', ')
    const vals = keys.map((k) => body.set![k])
    await c.env.DB.prepare(
      `UPDATE chess_games SET ${sets} WHERE id = ? AND group_id LIKE ?`
    )
      .bind(...vals, body.id, `${gid}%`)
      .run()
    return c.json({ ok: true })
  }

  return c.json({ error: 'unknown op' }, 400)
})

// 個人ステータス機能のテスト用エンドポイント。
// 読み取りは誰でも、書き込み(reset)はテスト用IDのみ。
app.post('/debug/profile', async (c) => {
  const body = (await c.req.json().catch(() => ({}))) as {
    op?: string
    userId?: string
    publicId?: string
    set?: Record<string, number | string | null>
  }
  const TEST_PREFIX = 'Upf_test_'

  if (body.op === 'get') {
    const row = await c.env.DB.prepare(`SELECT * FROM user_profiles WHERE user_id = ?`)
      .bind(body.userId ?? '')
      .first()
    const themes = await c.env.DB.prepare(`SELECT theme_id FROM user_themes WHERE user_id = ?`)
      .bind(body.userId ?? '')
      .all()
    const ledger = await c.env.DB.prepare(
      `SELECT delta, reason, reason_key FROM point_ledger WHERE user_id = ? ORDER BY id`
    )
      .bind(body.userId ?? '')
      .all()
    const titles = await c.env.DB.prepare(
      `SELECT title_id FROM user_common_titles WHERE user_id = ?`
    )
      .bind(body.userId ?? '')
      .all()
    return c.json({
      profile: row ?? null,
      themes: (themes.results ?? []).map((r: any) => r.theme_id),
      ledger: ledger.results ?? [],
      unlocked: (titles.results ?? []).map((r: any) => r.title_id),
    })
  }

  if (body.op === 'counts') {
    const t = await c.env.DB.prepare(`SELECT COUNT(*) c FROM common_title_master`).first<{ c: number }>()
    const cat = await c.env.DB.prepare(`SELECT COUNT(*) c FROM common_title_category`).first<{ c: number }>()
    const th = await c.env.DB.prepare(`SELECT COUNT(*) c FROM theme_master`).first<{ c: number }>()
    const byCat = await c.env.DB.prepare(
      `SELECT category, COUNT(*) c FROM common_title_master GROUP BY category`
    ).all()
    const byType = await c.env.DB.prepare(
      `SELECT unlock_type, COUNT(*) c FROM common_title_master GROUP BY unlock_type`
    ).all()
    // 既存のグループ別称号が壊れていないことも確認できるようにする
    const legacy = await c.env.DB.prepare(`SELECT COUNT(*) c FROM title_master`).first<{ c: number }>()
    const legacyUser = await c.env.DB.prepare(`SELECT COUNT(*) c FROM user_titles`).first<{ c: number }>()
    return c.json({
      titles: t?.c ?? 0,
      categories: cat?.c ?? 0,
      themes: th?.c ?? 0,
      byCategory: byCat.results ?? [],
      byType: byType.results ?? [],
      legacyTitleMaster: legacy?.c ?? 0,
      legacyUserTitles: legacyUser?.c ?? 0,
    })
  }

  const uid = body.userId ?? ''
  if (!uid.startsWith(TEST_PREFIX)) return c.json({ error: 'test users only' }, 403)

  if (body.op === 'reset') {
    for (const sql of [
      `DELETE FROM user_profiles WHERE user_id LIKE ?`,
      `DELETE FROM user_themes WHERE user_id LIKE ?`,
      `DELETE FROM point_ledger WHERE user_id LIKE ?`,
      `DELETE FROM user_common_titles WHERE user_id LIKE ?`,
      `DELETE FROM exp_events WHERE user_id LIKE ?`,
    ]) {
      await c.env.DB.prepare(sql).bind(`${uid}%`).run()
    }
    return c.json({ ok: true })
  }

  if (body.op === 'patch' && body.set) {
    const allowed = ['total_exp', 'points', 'active_theme', 'equipped_title']
    const keys = Object.keys(body.set).filter((k) => allowed.includes(k))
    if (keys.length === 0) return c.json({ error: 'no allowed keys' }, 400)
    const sets = keys.map((k) => `${k} = ?`).join(', ')
    await c.env.DB.prepare(`UPDATE user_profiles SET ${sets} WHERE user_id = ?`)
      .bind(...keys.map((k) => body.set![k]), uid)
      .run()
    return c.json({ ok: true })
  }

  return c.json({ error: 'unknown op' }, 400)
})

// 実際にLINEへ送ろうとした返信を数える。歓迎メッセージの二重送信テスト用。
// 自動テスト専用。テスト用IDの接頭辞に限定し、本番のグループでは動かない。
app.post('/debug/reply-logs', async (c) => {
  const { groupId, needle } = await c.req.json<{ groupId?: string; needle?: string }>()
  const gid = groupId ?? ''
  if (!gid.startsWith('Cpf_test_') && !gid.startsWith('Cmenu_test_')) {
    return c.json({ error: 'test ids only' }, 403)
  }
  try {
    const row = await c.env.DB.prepare(
      `SELECT COUNT(*) AS count FROM reply_api_logs
        WHERE group_id = ? AND message_preview LIKE ?`
    )
      .bind(gid, `%${needle ?? ''}%`)
      .first<{ count: number }>()
    return c.json({ count: row?.count ?? 0 })
  } catch (e: any) {
    return c.json({ error: String(e?.message ?? e) }, 500)
  }
})

// ヘルプメニューのPostbackが生成する内容を、LINEへ送らずに確認する。
// 自動テスト専用。テスト用IDの接頭辞に限定し、本番の利用者IDでは動かない。
app.post('/debug/menu', async (c) => {
  const { data, groupId, userId } = await c.req.json<{
    data: string
    groupId?: string
    userId?: string
  }>()
  if (!data) return c.json({ error: 'data is required' }, 400)
  const uid = userId ?? ''
  const gid = groupId ?? undefined
  // 本番の利用者・グループでは絶対に動かさない。
  const allowed =
    uid.startsWith('Umenu_test_') && (gid === undefined || gid.startsWith('Cmenu_test_'))
  if (!allowed) return c.json({ error: 'test ids only' }, 403)

  try {
    const result = await handleMenuPostback(
      c.env,
      {
        isGroup: gid !== undefined,
        groupId: gid,
        userId: uid,
        displayName: 'テスト利用者',
        siteUrl: SITE_URL,
      },
      data
    )
    let messages = result?.messages ?? []
    let ranExisting: string | null = null
    if (result?.runExisting) {
      ranExisting = result.runExisting
      messages = await routeCommand(c.env, {
        text: result.runExisting,
        isGroup: gid !== undefined,
        groupId: gid,
        userId: uid,
        displayName: 'テスト利用者',
        pictureUrl: null,
        baseUrl: new URL(c.req.url).origin,
      })
    }
    return c.json({
      would_reply_with: messages.slice(0, 5),
      ran_existing_command: ranExisting,
      note: 'これはLINEに送信されていません。',
    })
  } catch (e: any) {
    return c.json({ error: String(e?.message ?? e) }, 500)
  }
})

app.post('/debug/simulate', async (c) => {
  const { text, groupId, userId, pictureUrl } = await c.req.json<{
    text: string
    groupId?: string
    userId?: string
    pictureUrl?: string
  }>()
  if (!text) return c.json({ error: 'text is required' }, 400)

  const ctx = {
    text: text.trim(),
    isGroup: true,
    groupId: groupId ?? 'Cdebug_simulated_group',
    userId: userId ?? 'Udebug_simulated_user',
    displayName: 'デバッグユーザー',
    // Debug-only override so /debug/simulate can exercise the
    // "with avatar" quote-card code path too (e.g. imageGen.ts), not just
    // the no-avatar fallback. Defaults to null exactly as before.
    pictureUrl: pictureUrl ?? null,
    baseUrl: new URL(c.req.url).origin,
  }

  try {
    const directReplies = await routeCommand(c.env, ctx)
    const { messages: queued, ids: queuedIds } = await peekBroadcasts(c.env, ctx.groupId!)
    return c.json({
      input: { text: ctx.text, groupId: ctx.groupId, userId: ctx.userId },
      would_reply_with: [...directReplies, ...queued].slice(0, 5),
      pending_broadcast_queue_ids_not_yet_sent: queuedIds,
      note: 'これはLINEに送信されていません。ロジックが生成した返信内容の確認のみです。',
    })
  } catch (e: any) {
    return c.json({ error: String(e?.message ?? e) }, 500)
  }
})

// ─── LINE Webhook ───
app.post('/webhook', async (c) => {
  const bodyText = await c.req.text()
  const signature = c.req.header('x-line-signature') ?? null

  const valid = await verifySignature(c.env.LINE_CHANNEL_SECRET, bodyText, signature)

  await c.env.DB.prepare(
    `INSERT INTO webhook_debug_logs (timestamp, request_body, has_signature, event_type) VALUES (?, ?, ?, ?)`
  )
    .bind(new Date().toISOString(), bodyText.slice(0, 2000), signature ? 1 : 0, valid ? 'valid' : 'invalid_signature')
    .run()

  if (!valid) return c.json({ error: 'invalid signature' }, 401)

  const payload = JSON.parse(bodyText) as { events: any[] }
  const events = payload.events ?? []

  // IMPORTANT: LINE's webhook connection has a short timeout. We must ACK
  // (return 200) immediately after verifying the signature — NOT after
  // finishing all the DB writes / profile fetches / Reply API calls.
  // Otherwise LINE cancels the connection before we ever call Reply API,
  // which is exactly why real LINE traffic showed up as
  // `outcome: "canceled"` (cpuTime≈4ms, wallTime≈2000ms) in the tail logs
  // while our own sandbox curl requests (which just wait patiently) always
  // succeeded. So: respond first, then keep processing in the background
  // via waitUntil so the replyToken is still fresh when we use it.
  const baseUrl = new URL(c.req.url).origin

  const work = (async () => {
    for (const event of events) {
      try {
        await handleEvent(c.env, event, baseUrl)
      } catch (e: any) {
        await c.env.DB.prepare(
          `INSERT INTO webhook_debug_logs (timestamp, request_body, has_signature, event_type, error_message) VALUES (?, ?, ?, ?, ?)`
        )
          .bind(new Date().toISOString(), JSON.stringify(event).slice(0, 2000), 1, event.type, String(e?.message ?? e))
          .run()
      }
    }
  })()

  // 自動テスト専用の同期モード。waitUntil は応答後に走るため、テスト側から
  // 「処理が終わったか」を知る手段が無く、固定の待ち時間に頼ると不安定になる。
  // テスト用のID(下の接頭辞)のイベントだけに限定し、処理完了まで待ってから
  // 200を返す。実LINEのトラフィックは必ずこれらの接頭辞にならないため、
  // 本番の挙動は一切変わらない。
  // 個人トーク(source.type === 'user')のテストもあるため、
  // グループIDだけでなくユーザーIDの接頭辞も見る。
  const TEST_ID_PREFIXES = ['Cchess_test_', 'Cpf_test_', 'Upf_test_']
  const isTestEvent = (e: any) => {
    const gid = String(e?.source?.groupId ?? '')
    const uid = String(e?.source?.userId ?? '')
    return TEST_ID_PREFIXES.some((p) => gid.startsWith(p) || uid.startsWith(p))
  }
  const allTestEvents = events.length > 0 && events.every(isTestEvent)
  if (allTestEvents) {
    await work
    return c.json({ ok: true, sync: true })
  }

  c.executionCtx.waitUntil(work)

  return c.json({ ok: true })
})

async function handleEvent(env: Bindings, event: any, baseUrl: string) {
  switch (event.type) {
    case 'unsend':
      await handleUnsend(env, event)
      return

    case 'message':
      await handleMessageEvent(env, event, baseUrl)
      return

    case 'postback':
      await handlePostback(env, event, baseUrl)
      return

    case 'memberJoined':
      await handleMemberJoined(env, event)
      return

    case 'join':
      if (event.source.type === 'group') {
        const groupId = event.source.groupId
        const summary = await getGroupSummary(env, groupId)
        await ensureGroupMetadata(env, groupId, summary?.groupName ?? null)
      }
      return

    case 'leave':
      // Previously unhandled (fell through to default/no-op): group_metadata
      // never recorded that the bot was removed from a group, so old rows
      // looked identical to currently-joined groups. Record left_at so we
      // can tell "currently joined" apart from "invited once, since removed".
      if (event.source.type === 'group') {
        await markGroupLeft(env, event.source.groupId)
        // チェスの進行中対局は中断として保存(勝敗はつけない)
        try {
          await onBotLeftGroup(env, event.source.groupId)
        } catch {
          /* チェスの中断処理失敗は既存処理に影響させない */
        }
      }
      return

    default:
      return
  }
}

async function handleMemberJoined(env: Bindings, event: any) {
  const groupId = event.source.groupId
  if (!groupId) return

  const joined = event.joined?.members ?? []

  // Webhook再送対策: 同じ memberJoined イベントを2回処理しない。
  // LINEは応答が遅い・失敗したと判断すると同じイベントを再送するため、
  // 重複排除が無いと歓迎メッセージが2通続けて出てしまう(実際に発生した)。
  //
  // webhookEventId が無いイベントでも取りこぼさないよう、
  // 「グループ + 参加した人 + 分単位の時刻」でも一度だけに絞る。
  // (markEventProcessed は ID が null のとき素通りさせる作りのため)
  const idKey = event.webhookEventId
    ? `mj_${event.webhookEventId}`
    : `mj_${groupId}_${joined.map((m: any) => m?.userId ?? '?').sort().join('_')}_${Math.floor(
        (event.timestamp ?? Date.now()) / 60000
      )}`
  const fresh = await markEventProcessed(env, idKey)
  if (!fresh) return
  const resolved = await Promise.all(
    joined.map(async (m: any) => {
      const p = await getProfile(env, m.userId, groupId)
      return { userId: m.userId, displayName: p?.displayName }
    })
  )
  const messages = await buildWelcomeMessages(env, groupId, resolved)
  if (messages && event.replyToken) {
    await flushQueueOnReply(env, groupId, event.replyToken, messages)
  }
}

async function handleMessageEvent(env: Bindings, event: any, baseUrl: string) {
  const source = event.source
  const isGroup = source.type === 'group'
  const groupId = source.groupId
  const userId = source.userId
  const replyToken: string | undefined = event.replyToken
  const message = event.message

  let displayName: string | null = null
  let pictureUrl: string | null = null
  if (userId) {
    const profile = await getProfile(env, userId, isGroup ? groupId : undefined)
    displayName = profile?.displayName ?? null
    pictureUrl = profile?.pictureUrl ?? null
  }

  // 個人ステータスのEXP/ポイント加算(追加機能)。
  //   ・本人が新しく送った1通につき EXP+1・ポイント+1。
  //   ・種類(文章/画像/スタンプ/コマンド)で除外しない。
  //   ・グループと個人トークの両方が対象。
  //   ・獲得制限は付けない。ただし「1通を1回と数える」ため、
  //     webhookEventId(無ければ message.id)で二重加算だけ防ぐ。
  //   ・Bot自身の返信やボタン操作(Postback)はここを通らないので加算されない。
  // 失敗しても既存処理を止めないよう try/catch で完全に隔離する。
  if (userId) {
    try {
      const eventKey = event.webhookEventId ?? (message?.id ? `msg_${message.id}` : null)
      await addExpForMessage(env, userId, eventKey, displayName, pictureUrl)
    } catch {
      /* EXP加算の失敗は既存機能に影響させない */
    }
  }

  if (isGroup) {
    // Only call the LINE Group Summary API when we don't have a name yet
    // for this group — avoids hitting that endpoint on every single
    // message once group_name is populated.
    const existingMeta = await env.DB.prepare(`SELECT group_name FROM group_metadata WHERE group_id = ?`)
      .bind(groupId)
      .first<{ group_name: string | null }>()
    let groupName = existingMeta?.group_name ?? null
    if (!groupName) {
      const summary = await getGroupSummary(env, groupId)
      groupName = summary?.groupName ?? null
    }
    await ensureGroupMetadata(env, groupId, groupName)
    await touchGroupMember(env, groupId, userId, displayName)

    // ランキングの「主な活動時間帯」用の時間帯別集計(追加機能)。
    // 既存の touchGroupMember には一切手を入れず、新テーブルにだけ積む。
    // recordHourlyActivity は内部で例外を飲むが、万一に備えてここでも
    // 囲い、この集計の失敗が Bot 本体の処理を止めないようにする。
    try {
      await recordHourlyActivity(env, groupId)
    } catch {
      /* ranking の集計失敗は既存機能に影響させない */
    }

    if (message.type === 'text') {
      await cacheGroupMessage(env, groupId, message.id, userId, displayName, pictureUrl, message.text)
    }

    // Lazily check push-free scheduled-ish features (no cron available).
    await checkAndQueueBirthdays(env, groupId)
    // 運勢の自動配信は廃止した(機能ごと削除)。
    await checkAndQueueWeeklyRanking(env, groupId)
    // 未送信のお知らせをグループごとに1回だけ配信する。
    // キューに積むだけなので Push API は使わず、実送信はこの発言への
    // Reply に便乗する。失敗しても他の機能を巫がないよう try/catch で囲う。
    try {
      await checkAndQueueAnnouncements(env, groupId)
    } catch {
      /* お知らせ配信の失敗は既存機能に影響させない */
    }
    // Any message (not just othello commands or board taps) can be the
    // trigger that notices an abandoned in-progress game and announces its
    // timeout — there's no cron/push to do this proactively.
    await checkAndQueueOthelloTimeout(env, groupId)
  }

  if (message.type !== 'text' || !replyToken) {
    // Still flush any queued broadcasts if we at least have a replyToken.
    if (replyToken && isGroup) await flushQueueOnReply(env, groupId, replyToken, [])
    return
  }

  const text: string = message.text.trim()
  const directReplies = await routeCommand(env, {
    text,
    isGroup,
    groupId,
    userId,
    displayName,
    pictureUrl,
    baseUrl,
    quotedMessageId: message.quotedMessageId,
  })

  if (isGroup) {
    await flushQueueOnReply(env, groupId, replyToken, directReplies)
  } else if (directReplies.length > 0) {
    await replyMessage(env, replyToken, directReplies, userId)
  }
}

// Handles taps on the Othello board (a `postback` action on a legal-move
// cell). Reply-only: the postback event carries its own one-time
// replyToken, exactly like a message event, so this never needs Push API.
async function handlePostback(env: Bindings, event: any, baseUrl: string) {
  const source = event.source
  const userId = source.userId
  const replyToken: string | undefined = event.replyToken
  const data: string = event.postback?.data ?? ''

  // --- 個人ステータス・着せ替え・共通称号(追加機能) ---
  // グループでも個人トークでも動かす必要があるため、
  // 既存のグループ限定チェックより前に処理する。
  //
  // 操作主体は必ず source.userId。PostbackのデータにユーザーIDは
  // 入っていないので、他人のカードのボタンを押しても、そのカードの
  // 持ち主のポイント・装備は一切変わらず、押した本人の画面が出る。
  if (data.startsWith('pf|') && userId && replyToken) {
    // Webhook再送・連打対策: 同じ webhookEventId は1回だけ処理する。
    // (購入の二重成立は point_ledger の一意制約でも防いでいる)
    const fresh = await markEventProcessed(env, event.webhookEventId ?? null)
    if (!fresh) return
    try {
      const msgs = await handleProfilePostback(
        env,
        {
          userId,
          displayName: null,
          pictureUrl: null,
          baseUrl,
        },
        data
      )
      if (msgs && msgs.length > 0) {
        if (source.type === 'group' && source.groupId) {
          await flushQueueOnReply(env, source.groupId, replyToken, msgs.slice(0, 5))
        } else {
          await replyMessage(env, replyToken, msgs.slice(0, 5))
        }
      }
    } catch {
      await replyMessage(env, replyToken, [
        { type: 'text', text: 'この操作でエラーが発生しました。「ステータス」で開き直せます。' },
      ])
    }
    return
  }

  // --- ヘルプメニュー(横スワイプのカルーセルと案内画面) ---
  // グループでも個人トークでも動くよう、グループ限定チェックより前に置く。
  //
  // 操作主体は必ず source.userId。トークンにユーザーIDは入っていない。
  // 「メニューを開く」だけの操作では状態を変えない。設定変更は確認をはさみ、
  // 確認意図はサーバー(menu_confirmations)に保存して本人・グループ・期限を
  // 照合してから、既存コマンドの処理をそのまま呼ぶ。
  if (data.startsWith('hm|') && userId && replyToken) {
    // Webhook再送・連打対策: 同じ webhookEventId は1回だけ処理する。
    const fresh = await markEventProcessed(env, event.webhookEventId ?? null)
    if (!fresh) return
    const isGroup = source.type === 'group'
    const gid: string | undefined = isGroup ? source.groupId : undefined
    try {
      const profile = await getProfile(env, userId, gid)
      const result = await handleMenuPostback(
        env,
        {
          isGroup,
          groupId: gid,
          userId,
          displayName: profile?.displayName ?? null,
          siteUrl: SITE_URL,
        },
        data
      )
      let msgs = result?.messages ?? []
      // 表示だけの既存コマンドは、既存の routeCommand をそのまま通す。
      // これにより既存のカード・文言・内部処理を作り直さずに再利用する。
      if (result?.runExisting) {
        msgs = await routeCommand(env, {
          text: result.runExisting,
          isGroup,
          groupId: gid,
          userId,
          displayName: profile?.displayName ?? null,
          pictureUrl: profile?.pictureUrl ?? null,
          baseUrl,
        })
      }
      if (msgs.length > 0) {
        if (isGroup && gid) {
          await flushQueueOnReply(env, gid, replyToken, msgs.slice(0, 5))
        } else {
          await replyMessage(env, replyToken, msgs.slice(0, 5))
        }
      }
    } catch {
      await replyMessage(env, replyToken, [
        { type: 'text', text: 'この操作でエラーが発生しました。「ヘルプ」で開き直せます。' },
      ])
    }
    return
  }

  // 以下はグループ限定の既存処理(チェス・オセロ)。
  if (source.type !== 'group') return
  const groupId = source.groupId
  if (!groupId || !userId || !replyToken) return

  // --- チェス ---
  // data が c で始まるチェス用トークンのときだけ処理する。
  // 本人確認は Postback の中身ではなく source.userId で行う(handleChessPostback内)。
  if (/^c[a-z]{1,2}\|/.test(data)) {
    // Webhook再送・二重タップ対策: 同じ webhookEventId は1回だけ処理する
    const fresh = await markEventProcessed(env, event.webhookEventId ?? null)
    if (!fresh) return
    try {
      const msgs = await handleChessPostback(
        env,
        { groupId, userId, baseUrl },
        data
      )
      if (msgs && msgs.length > 0) {
        await flushQueueOnReply(env, groupId, replyToken, msgs.slice(0, 1))
      }
    } catch (e: any) {
      await flushQueueOnReply(env, groupId, replyToken, [
        { type: 'text', text: 'チェスの処理でエラーが発生しました。「盤面」で最新の状態を確認できます。' },
      ])
    }
    return
  }

  const othelloMatch = data.match(/^othello:(\d+),(\d+)$/)
  if (othelloMatch) {
    const row = Number(othelloMatch[1])
    const col = Number(othelloMatch[2])
    const profile = await getProfile(env, userId, groupId)
    const result = await applyOthelloMove(env, groupId, userId, row, col, profile?.displayName ?? null)
    // "silent" rejections (same user re-tapping within 5s of their last
    // rejected tap, e.g. "相手の番です。" spam) intentionally send NOTHING —
    // not even to flush the broadcast queue, since a tap isn't a real
    // message and shouldn't be the trigger for unrelated queued notices.
    if (!result.ok && result.silent) return
    const message = result.ok
      ? buildOthelloMessage(result.game, result.note)
      : { type: 'text', text: result.reason }
    await flushQueueOnReply(env, groupId, replyToken, [message])
  }
}

// Combine (a) any direct reply this command produced with (b) whatever is
// sitting in the push-free broadcast queue for this group, then send it all
// in ONE free Reply call (LINE allows up to 5 messages per reply).
//
// IMPORTANT: queued broadcasts are only marked delivered AFTER we confirm
// the reply call actually succeeded. If the reply fails (expired/invalid
// replyToken, network error, etc.) the broadcast rows stay pending and will
// be retried on the next incoming message — nothing is silently lost.
async function flushQueueOnReply(env: Bindings, groupId: string, replyToken: string, direct: LineMessage[]) {
  const { messages: queued, ids: queuedIds } = await peekBroadcasts(env, groupId)
  const combined = [...direct, ...queued].slice(0, 5)
  if (combined.length === 0) return

  const result = await replyMessage(env, replyToken, combined, groupId)
  if (result.ok) {
    await markBroadcastsDelivered(env, queuedIds)
  }
  // If it failed, direct replies are lost (nothing we can do — the
  // replyToken is already spent/invalid either way), but queued broadcasts
  // remain pending and will be included in the next reply attempt.
}

interface CommandCtx {
  text: string
  isGroup: boolean
  groupId?: string
  userId?: string
  displayName: string | null
  pictureUrl: string | null
  baseUrl: string
  quotedMessageId?: string
}

async function routeCommand(env: Bindings, ctx: CommandCtx): Promise<LineMessage[]> {
  const { text } = ctx

  // 固定テストコマンド。今後は言葉を変えず、これだけで動作確認する。
  if (text === 'テスト') {
    return [{ type: 'text', text: `テスト成功 (${new Date().toISOString()})` }]
  }

  // `ヘルプ` は横スワイプのメニューカルーセルを出す。
  // 文字のコマンド一覧は、メニューの「ガイド → 全コマンド」から見られる。
  // 既存の別名 `help` もそのまま同じ扱い。新しい呼び名は追加していない。
  // メニューの組み立てに失敗しても、従来のテキストヘルプへ必ず落ちる。
  if (text === 'ヘルプ' || text.toLowerCase() === 'help') {
    try {
      const menu = handleMenuText(
        {
          isGroup: ctx.isGroup,
          groupId: ctx.groupId,
          userId: ctx.userId,
          displayName: ctx.displayName,
          siteUrl: SITE_URL,
        },
        text === 'ヘルプ' ? 'ヘルプ' : 'help'
      )
      if (menu && menu.length > 0) return menu
    } catch {
      /* メニューの不具合でヘルプ自体が止まらないよう、下のテキストへ落ちる */
    }
    return [{ type: 'text', text: HELP_TEXT }]
  }

  // --- 個人ステータス・着せ替え・共通称号(追加機能) ---
  // 「ステータス」「着せ替え」「共通称号一覧」「共通称号装備」
  // 「共通称号確認」「称号検索」だけに反応する。
  // 既存の「称号一覧」「称号装備」「称号確認」はグループ別称号のまま
  // 下の方で処理されるので、ここでは触らない。
  // グループでも個人トークでも使える(個人トークへ誘導しない)。
  // 失敗しても他のコマンドを止めないよう try/catch で囲う。
  if (ctx.userId) {
    try {
      const pfMsgs = await handleProfileText(
        env,
        {
          userId: ctx.userId,
          displayName: ctx.displayName,
          pictureUrl: ctx.pictureUrl,
          baseUrl: ctx.baseUrl,
        },
        text
      )
      if (pfMsgs) return pfMsgs
    } catch {
      /* 個人ステータス機能の失敗は既存コマンドに影響させない */
    }
  }

  // --- チェス(グループ対局) ---
  // 「チェス」「盤面」「チェス ヘルプ」だけに反応し、それ以外の会話には
  // 一切反応しない(handleChessText が null を返す)。
  // グループ以外(個別トーク)では導入方法を案内する。
  if (text === 'チェス' || text === '盤面' || text === 'チェス ヘルプ' || text === 'チェスヘルプ') {
    if (!ctx.isGroup || !ctx.groupId) {
      return [
        {
          type: 'text',
          text:
            'チェスはグループトークで対局する機能です。\n\n' +
            '使い方:\n' +
            '1. このBOTをグループに招待する\n' +
            '2. グループで「チェス」と送る\n' +
            '3. 別の人が「対局に参加」を押すと開始\n\n' +
            '※オープンチャットには対応していません。\n' +
            '※ルールは「チェス ヘルプ」で確認できます。',
        },
      ]
    }
    try {
      const chessMsgs = await handleChessText(
        env,
        { groupId: ctx.groupId, userId: ctx.userId ?? null, baseUrl: ctx.baseUrl },
        text
      )
      if (chessMsgs) return chessMsgs
    } catch {
      return [{ type: 'text', text: 'チェスの処理でエラーが発生しました。もう一度お試しください。' }]
    }
  }

  // グループ発言数ランキング。既存に同名コマンドは存在しない
  // (週間個人ランキングは自動配信で、コマンドは未実装だった)ので
  // 新規追加している。失敗しても他の応答を巫がないよう try/catch で囲う。
  if ((text === 'ランキング' || text === '順位') && ctx.isGroup && ctx.groupId) {
    try {
      const reply = await buildGroupRankingReply(env, ctx.groupId, SITE_URL)
      return [{ type: 'text', text: reply }]
    } catch {
      return [{ type: 'text', text: 'ランキングの取得に失敗しました。' }]
    }
  }

  if (text === 'お知らせ') {
    const messages = getLatestAnnouncementMessages(ctx.isGroup ? ctx.groupId ?? null : null)
    if (messages.length === 0) return [{ type: 'text', text: '現在お知らせはありません。' }]
    return messages
  }

  // 運勢機能(「運勢」「今日の運勢」「星座登録」「星座登録解除」)は削除した。
  // 毎日の自動配信がグループの会話に割り込んでうっとうしいという指摘を受け、
  // まず自動配信を止め、続いて機能そのものを廃止した。
  // ・src/features/fortune.ts は削除済み
  // ・DBのテーブル(user_zodiac_signs / daily_fortunes / daily_fortune_sent)は
  //   既存データを壊さない方針に従い残してある。特に daily_fortune_sent は
  //   誕生日機能が「birthday_<groupId>」というキーで流用しているため、
  //   消すと誕生日のお祝いが毎回重複送信されるようになる。絶対に消さない。

  const birthdayMatch = text.match(/^誕生日登録\s*(\d{1,2})\/(\d{1,2})$/)
  if (birthdayMatch && ctx.isGroup && ctx.groupId && ctx.userId) {
    const month = parseInt(birthdayMatch[1], 10)
    const day = parseInt(birthdayMatch[2], 10)
    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
      await registerBirthday(env, ctx.groupId, ctx.userId, ctx.displayName ?? '不明', month, day)
      return [{ type: 'text', text: `誕生日を${month}/${day}として登録しました` }]
    }
    return [{ type: 'text', text: '日付の形式が正しくありません。例: 誕生日登録 4/1' }]
  }

  if (text === '誕生日登録解除' && ctx.isGroup && ctx.groupId && ctx.userId) {
    const removed = await unregisterBirthday(env, ctx.groupId, ctx.userId)
    return [{ type: 'text', text: removed ? '誕生日の登録を解除しました' : '誕生日は登録されていません' }]
  }

  if (text === '取り消し通知オフ' && ctx.isGroup && ctx.groupId) {
    await env.DB.prepare(
      `INSERT INTO unsend_restore_settings (group_id, enabled) VALUES (?, 0)
       ON CONFLICT(group_id) DO UPDATE SET enabled = 0, updated_at = CURRENT_TIMESTAMP`
    )
      .bind(ctx.groupId)
      .run()
    return [{ type: 'text', text: '取り消し通知をオフにしました' }]
  }

  if (text === '取り消し通知オン' && ctx.isGroup && ctx.groupId) {
    await env.DB.prepare(
      `INSERT INTO unsend_restore_settings (group_id, enabled) VALUES (?, 1)
       ON CONFLICT(group_id) DO UPDATE SET enabled = 1, updated_at = CURRENT_TIMESTAMP`
    )
      .bind(ctx.groupId)
      .run()
    return [{ type: 'text', text: '取り消し通知をオンにしました' }]
  }

  if (text === 'ウェルカムオフ' && ctx.isGroup && ctx.groupId) {
    await setWelcomeSetting(env, ctx.groupId, false)
    return [{ type: 'text', text: 'ウェルカムメッセージをオフにしました' }]
  }
  if (text === 'ウェルカムオン' && ctx.isGroup && ctx.groupId) {
    await setWelcomeSetting(env, ctx.groupId, true)
    return [{ type: 'text', text: 'ウェルカムメッセージをオンにしました' }]
  }
  const welcomeMsgMatch = text.match(/^ウェルカムメッセージ設定\s*(.+)$/s)
  if (welcomeMsgMatch && ctx.isGroup && ctx.groupId) {
    await setWelcomeSetting(env, ctx.groupId, true, welcomeMsgMatch[1].trim())
    return [{ type: 'text', text: 'ウェルカムメッセージを設定しました' }]
  }
  if (text === 'ウェルカムメッセージ解除' && ctx.isGroup && ctx.groupId) {
    await clearWelcomeMessage(env, ctx.groupId)
    return [{ type: 'text', text: 'カスタムウェルカムメッセージを解除しました(デフォルトの歓迎文に戻ります)' }]
  }

  // Reply mode: bare "めいく" (no colon/text) sent as a LINE reply to someone
  // else's message. quotedMessageId points at the ORIGINAL message, so the
  // card must use ITS author's name/icon and ITS text — not the replier's.
  // 装飾の一覧。返信モードの判定より先に置く必要がある
  // (「めいく 装飾」が返信モードのパラメータとして食われないようにする)。
  if (/^めいく[ 　]*(装飾|ヘルプ|help)$/i.test(text)) {
    const fontList = Object.entries(FONT_LABELS)
      .map(([n, l]) => `${n}:${l}`)
      .join(' / ')
    return [
      {
        type: 'text',
        text:
          '名言カードの装飾\n\n' +
          '【書き方】\n' +
          'めいく[装飾]:[テキスト]\n' +
          '返信のときは「めいく[装飾]」\n' +
          'スペースはあってもなくてもOK\n' +
          '装飾は続けて書けます（例: newbold虹7）\n\n' +
          '【見た目】\n' +
          'bold … 文字を太字\n' +
          'rev … アイコンを左右反転\n' +
          'mono … アイコンを白黒\n' +
          'whi … 白ベースで生成\n' +
          'new … 新レイアウト（右上に日付）\n\n' +
          '【色】\n' +
          '虹 … 1文字ずつ虹色\n' +
          '赤 橙 黄 緑 青 藍 紫 桃 水 白 黒 金 銀\n' +
          '春 夏 秋 冬 … 季節テーマ（1文字ずつ変化）\n' +
          '#FF00AA … 好きな色コード\n\n' +
          '【フォント 1〜12】\n' +
          fontList +
          '\n\n【例】\n' +
          'めいく虹:やったー\n' +
          'めいくbold虹:やったー\n' +
          'めいくnew7:静かな夜\n' +
          'めいくwhi#0088FF:おはよう\n' +
          'めいくrevmono （他人の発言に返信して）',
      },
    ]
  }

  // 返信モード: 「めいく」または「めいく<装飾>」を他人の発言への
  // 返信として送る。装飾部分(bold, mono, 虹, 3 など)は任意で、
  // 無指定なら従来と完全に同じカードになる。
  // スペースは任意 —「めいく虹」「めいく 虹」のどちらでも同じ。
  // スペース無しを許すと「めいくで作った」「めいくしたい」のような
  // ふつうの会話にも一致してしまうため、続く文字列が丸ごと装飾として
  // 解釈できた場合(または何も続かない場合)だけコマンドとして扱う。
  const replyMake = text.match(/^めいく[ 　]*(.*)$/s)
  if (
    replyMake &&
    isPureParamString(replyMake[1]) &&
    ctx.isGroup &&
    ctx.groupId &&
    ctx.quotedMessageId
  ) {
    const original = await getGroupMessage(env, ctx.groupId, ctx.quotedMessageId)
    if (!original) {
      return [{ type: 'text', text: '元のメッセージが見つかりませんでした(古すぎるか、記録前の発言かもしれません)' }]
    }
    const params = parseQuoteParams(replyMake[1] ?? null)
    const imageId = await saveQuote(
      env,
      ctx.groupId,
      original.user_id,
      original.display_name ?? '不明',
      original.picture_url,
      original.message_text,
      { params, baseUrl: ctx.baseUrl }
    )
    return [buildQuoteImageMessage(ctx.baseUrl, imageId)]
  }

  // 通常モード: 「めいく:テキスト」「めいく<装飾>:テキスト」。
  // スペースは任意 —「めいく虹:あ」「めいく 虹:あ」のどちらでも同じ。
  // 装飾は最初の「:」までの部分だけを見る(本文に「:」が含まれても、
  //   最初の1個だけを区切りにする)。
  // 装飾部分と区切り文字を別々に捕獲する。区切り文字を捕獲しておくのは、
  // 装飾として解釈できなかったときに元の文字列を正しく復元するため
  // (「めいくで作った:test」の本文は「で作った:test」でなければならない)。
  const quoteMatch = text.match(/^めいく[ 　]*([^:：]*)([:：])\s*(.+)$/s)
  if (quoteMatch && ctx.isGroup && ctx.groupId && ctx.userId) {
    // 「:」の前の文字列が丸ごと装飾として解釈できたときだけ装飾と見なす。
    // 解釈できない文字が混じっている場合は装飾ではなく本文の一部として
    // 扱う(勝手に装飾を当てない)。
    const rawParam = quoteMatch[1] ?? ''
    const sep = quoteMatch[2]
    const isParam = isPureParamString(rawParam)
    const params = parseQuoteParams(isParam ? rawParam : null)
    const quoteText = (isParam ? quoteMatch[3] : `${rawParam}${sep}${quoteMatch[3]}`).trim()
    const imageId = await saveQuote(
      env,
      ctx.groupId,
      ctx.userId,
      ctx.displayName ?? '不明',
      ctx.pictureUrl,
      quoteText,
      { params, baseUrl: ctx.baseUrl }
    )
    return [buildQuoteImageMessage(ctx.baseUrl, imageId)]
  }

  if (text === 'オセロ開始' && ctx.isGroup && ctx.groupId && ctx.userId) {
    const result = await startOthello(env, ctx.groupId, ctx.userId, ctx.displayName)
    if (!result.ok) return [{ type: 'text', text: result.reason }]
    // If starting this game just cleaned up a previous game that had timed
    // out from 5+ minutes of inactivity, mention that before the new board.
    const messages: LineMessage[] = []
    if (result.timeoutMessage) messages.push({ type: 'text', text: result.timeoutMessage })
    messages.push(buildOthelloMessage(result.game))
    return messages
  }

  if (text === 'オセロ参加' && ctx.isGroup && ctx.groupId && ctx.userId) {
    const result = await joinOthello(env, ctx.groupId, ctx.userId, ctx.displayName)
    if (!result.ok) return [{ type: 'text', text: result.reason }]
    return [buildOthelloMessage(result.game)]
  }

  if (text === 'オセロ終了' && ctx.isGroup && ctx.groupId && ctx.userId) {
    const result = await endOthello(env, ctx.groupId, ctx.userId)
    return [{ type: 'text', text: result.ok ? 'オセロを終了しました' : result.reason }]
  }

  if (text === 'オセロ戦績' && ctx.isGroup && ctx.groupId && ctx.userId) {
    const record = await getOthelloRecord(env, ctx.groupId, ctx.userId)
    if (!record) return [{ type: 'text', text: 'まだ対局結果がありません' }]
    return [{ type: 'text', text: `オセロ戦績\n勝ち: ${record.wins}\n負け: ${record.losses}\n引き分け: ${record.draws}` }]
  }

  const tagAddMatch = text.match(/^タグ追加\s*(.+)$/)
  if (tagAddMatch && ctx.isGroup && ctx.groupId) {
    await addTagToGroup(env, ctx.groupId, tagAddMatch[1].trim())
    return [{ type: 'text', text: `タグ「${tagAddMatch[1].trim()}」を追加しました` }]
  }
  const tagRemoveMatch = text.match(/^タグ削除\s*(.+)$/)
  if (tagRemoveMatch && ctx.isGroup && ctx.groupId) {
    await removeTagFromGroup(env, ctx.groupId, tagRemoveMatch[1].trim())
    return [{ type: 'text', text: `タグ「${tagRemoveMatch[1].trim()}」を削除しました` }]
  }
  if (text === 'タグ一覧' && ctx.isGroup && ctx.groupId) {
    const tags = await listGroupTags(env, ctx.groupId)
    return [{ type: 'text', text: tags.length > 0 ? `タグ: ${tags.join('、')}` : 'タグは設定されていません' }]
  }

  if (text === '称号一覧' && ctx.isGroup && ctx.groupId && ctx.userId) {
    const titles = await listUserTitles(env, ctx.userId, ctx.groupId)
    if (titles.length === 0) return [{ type: 'text', text: '所持している称号はありません' }]
    const equipped = await getEquippedTitle(env, ctx.userId, ctx.groupId)
    const lines = titles.map((t) => (t === equipped ? `★${t}（装備中）` : `・${t}`))
    return [{ type: 'text', text: `所持称号一覧\n${lines.join('\n')}` }]
  }

  const equipMatch = text.match(/^称号装備\s*(.+)$/)
  if (equipMatch && ctx.isGroup && ctx.groupId && ctx.userId) {
    const titleName = equipMatch[1].trim()
    const owned = await listUserTitles(env, ctx.userId, ctx.groupId)
    if (!owned.includes(titleName)) {
      return [{ type: 'text', text: `「${titleName}」は所持していません` }]
    }
    await equipTitle(env, ctx.userId, ctx.groupId, titleName)
    return [{ type: 'text', text: `称号「${titleName}」を装備しました` }]
  }

  if (text === '称号確認' && ctx.isGroup && ctx.groupId && ctx.userId) {
    const equipped = await getEquippedTitle(env, ctx.userId, ctx.groupId)
    return [{ type: 'text', text: equipped ? `装備中の称号: ${equipped}` : '称号は装備していません' }]
  }

  return []
}

const HELP_TEXT = `葉っぱもち Bot ヘルプ

【基本】
ヘルプ - このメッセージを表示
お知らせ - 最新のお知らせを確認

【ランキング】
ランキング - このグループの今週の順位と発言数を確認

【チェス】
チェス - 対局相手を募集(グループ内の2人で対局)
盤面 - 現在の盤面を再送
チェス ヘルプ - 操作方法と採用ルール

【誕生日】
誕生日登録 [月]/[日] - 誕生日を登録(自動でお祝い通知)
誕生日登録解除 - 誕生日の登録を解除

【取り消し通知】
メッセージが削除されると自動で通知(取り消し通知オフ/オンで切替)

【ウェルカム】(初期はオフ)
ウェルカムオン - 新メンバーへの歓迎メッセージを送る
ウェルカムオフ - 送らないようにする(初期状態)
ウェルカムメッセージ設定 [本文] - カスタム歓迎文を設定
ウェルカムメッセージ解除 - カスタム歓迎文を解除してデフォルトに戻す

【名言カード】
めいく:[テキスト] - 名言カードを生成
(他人のメッセージに「返信(リプライ)」で「めいく」だけ送ると、その人の名言カードを生成)

めいく[装飾]:[テキスト] のように装飾を足せます
返信のときは「めいく[装飾]」と送ります
(スペースはあってもなくてもOK)
・見た目: bold(太字) rev(アイコン反転) mono(アイコン白黒)
　　　　　whi(白ベース) new(新レイアウト・日付付き)
・色: 虹 / 赤 橙 黄 緑 青 藍 紫 桃 水 白 黒 金 銀
　　　春 夏 秋 冬(季節テーマ) / #FF00AA(自由な色)
・フォント: 1〜12
　1ゴシック 2太 3細 4中 5極太 6極細
　7明朝 8明朝太 9明朝細 10明朝極太 11明朝中 12等幅
続けて書けます 例)「めいくnewbold虹7:こんにちは」
「めいく装飾」で一覧を確認できます

【オセロ】
オセロ開始 - オセロを開始(自分が黒番になる)
オセロ参加 - 白番として参加
オセロ終了 - 対局を終了
オセロ戦績 - 自分の勝敗数を確認
盤面のマスをタップして石を置く

【タグ】
タグ追加/削除/一覧 [タグ名]

【称号(グループごと)】
称号一覧 - このグループで所持している称号を確認
称号装備 [称号名] - 称号を装備
称号確認 - 現在装備中の称号を確認

【ステータス・着せ替え・共通称号】
ステータス - レベル・EXP・順位・ポイントを表示
着せ替え - カードテーマを選ぶ(名言カードにも反映)
共通称号一覧 - 全300種類から称号を選ぶ
共通称号装備 [称号名] - 共通称号を装備
共通称号確認 - 装備中の共通称号を確認
称号検索 [文字] - 共通称号を名前で探す

メッセージを1通送るごとに 1EXP と 1ポイントがたまります。
必要EXPは「100 + 8 ×（現在のレベル − 1）」です。
共通称号はグループをまたいで共通、上の「称号」はグループごとです。
個人ランキングと公開ステータス: ${SITE_URL}/ranking/personal`

export default app
