import { Hono } from 'hono'
import { serveStatic } from 'hono/cloudflare-workers'
import {
  replyMessage,
  getProfile,
  getGroupSummary,
  verifySignature,
  peekBroadcasts,
  markBroadcastsDelivered,
  type LineEnv,
  type LineMessage,
} from './lib/line'
import { handleUnsend } from './features/unsend'
import { cacheGroupMessage, touchGroupMember, ensureGroupMetadata, markGroupLeft, getGroupMessage } from './features/groupTracking'
import { buildWelcomeMessages } from './features/welcome'
import { registerBirthday, unregisterBirthday, checkAndQueueBirthdays } from './features/birthday'
import {
  getOrCreateDailyFortune,
  formatFortuneText,
  registerZodiacSign,
  unregisterZodiacSign,
  todayJst,
  ZODIAC_SIGNS,
  checkAndQueueGroupFortune,
} from './features/fortune'
import { checkAndQueueWeeklyRanking } from './features/ranking'
import { saveQuote, buildQuoteImageMessage } from './features/quote'
import { addTagToGroup, listGroupTags, removeTagFromGroup } from './features/tags'
import { setWelcomeSetting, clearWelcomeMessage } from './features/welcome'
import { equipTitle, getEquippedTitle, listUserTitles } from './features/titles'
import { startGame as startOthello, joinGame as joinOthello, endGame as endOthello, applyMove as applyOthelloMove, buildOthelloMessage, checkAndQueueOthelloTimeout, getOthelloRecord } from './features/othello'
import { getLatestAnnouncementMessages } from './features/announcements'
import {
  listThreads,
  listAllThreadIds,
  getThread,
  incrementThreadViews,
  likeThread,
  createThread,
  listChatMessages,
  postChatMessage,
  listChatMessagesAfter,
  chatMessageToJson,
  listComments,
  postComment,
  isRateLimited,
  touchRateLimit,
  getStats,
  saveContactMessage,
  listGalleryImages,
  deleteGalleryImage,
  renderThreadsListPage,
  renderThreadDetailPage,
  renderNewThreadPage,
  renderChatPage,
  renderGuidePage,
  renderGalleryPage,
  renderGalleryAdminLoginPage,
  renderErrorPage,
  renderRssFeed,
  CATEGORIES,
  SORT_OPTIONS,
  SITE_URL,
} from './features/bbs'
import { isAdminRequest, createSessionToken, buildSessionCookie, buildLogoutCookie, isAdminConfigured } from './features/galleryAdmin'

type Bindings = LineEnv

const app = new Hono<{ Bindings: Bindings }>()

app.use('/static/*', serveStatic({ root: './public' }))

// ─── Health check ───
app.get('/', (c) => c.text('HappaMochi Bot is running'))

// ─── Quote card image delivery ───
// Public, unauthenticated, plain-HTTPS GET endpoint that LINE's servers
// fetch directly when rendering an imageMessage (originalContentUrl /
// previewImageUrl). Serves the PNG bytes generated by generateQuoteCardPng
// and stored in quote_images.image_data (see features/quote.ts).
app.get('/quote-image/:id', async (c) => {
  const id = c.req.param('id')
  const row = await c.env.DB.prepare(`SELECT image_data FROM quote_images WHERE id = ?`)
    .bind(id)
    .first<{ image_data: ArrayBuffer }>()
  if (!row) return c.notFound()
  // D1's local (workerd/miniflare) emulation sometimes returns a BLOB column
  // as a plain JS Array of byte values instead of an ArrayBuffer. Passing
  // that array straight into `new Response()` gets it silently stringified
  // (BodyInit coercion calls String()/Array.prototype.join on it), which is
  // exactly the "137,80,78,71,..." decimal-CSV corruption bug. Normalize to
  // a real ArrayBuffer regardless of which shape D1 handed back.
  const raw = row.image_data as unknown
  const bytes = Array.isArray(raw) ? Uint8Array.from(raw as number[]) : new Uint8Array(raw as ArrayBuffer)
  return new Response(bytes, {
    headers: {
      'Content-Type': 'image/png',
      'Cache-Control': 'public, max-age=31536000, immutable',
    },
  })
})

// ─── 名言カードギャラリー ───
// 「めいく」コマンドで生成された名言カード(quote_images)を一覧表示する
// 公開ページ。画像本体は上の /quote-image/:id を<img src>としてそのまま
// 使うだけで、新しい画像配信経路は追加しない。LINE Bot側のコマンド処理
// (index.tsx内のmeイクcommand handler / features/quote.ts)には一切触れない。
app.get('/gallery', async (c) => {
  const page = Math.max(1, parseInt(c.req.query('page') || '1', 10) || 1)
  const result = await listGalleryImages(c.env, page)
  const admin = await isAdminRequest(c.env, c.req.header('Cookie'))
  return c.html(renderGalleryPage(result, admin))
})

// ─── ギャラリー管理者ログイン/ログアウト/削除 ───
// LINE Bot本体(webhook, quote.ts, imageGen.ts)には一切関与しない、
// /gallery/admin* 専用の独立した認証・削除フロー。パスワードは
// Cloudflare のシークレット GALLERY_ADMIN_PASSWORD にのみ保存される。
app.get('/gallery/admin', async (c) => {
  const admin = await isAdminRequest(c.env, c.req.header('Cookie'))
  if (admin) return c.redirect('/gallery')
  if (!isAdminConfigured(c.env)) {
    return c.html(renderGalleryAdminLoginPage('管理者ログインは現在設定されていません。'), 503)
  }
  return c.html(renderGalleryAdminLoginPage())
})

app.post('/gallery/admin', async (c) => {
  const key = await clientKeyFor(c, 'gallery-admin-login')
  if (await isRateLimited(c.env, key)) {
    return c.html(renderGalleryAdminLoginPage('試行間隔が短すぎます。しばらく待ってから再度お試しください。'), 429)
  }
  await touchRateLimit(c.env, key)

  const body = await c.req.parseBody()
  const password = String(body.password ?? '')
  const token = await createSessionToken(c.env, password)
  if (!token) {
    return c.html(renderGalleryAdminLoginPage('パスワードが正しくありません。'), 401)
  }
  c.header('Set-Cookie', buildSessionCookie(token))
  return c.redirect('/gallery')
})

app.post('/gallery/admin/logout', async (c) => {
  c.header('Set-Cookie', buildLogoutCookie())
  return c.redirect('/gallery')
})

app.post('/gallery/admin/delete/:id', async (c) => {
  const admin = await isAdminRequest(c.env, c.req.header('Cookie'))
  if (!admin) return c.json({ error: 'unauthorized' }, 401)
  const id = c.req.param('id')
  const deleted = await deleteGalleryImage(c.env, id)
  if (!deleted) return c.json({ error: 'not found' }, 404)
  return c.json({ ok: true })
})

// ─── LINEグループ募集掲示板 (BBS) + オープンチャット ───
// Public, unauthenticated GET/POST website reading from (and preserving)
// the historical `threads` / `chat_messages` tables — see features/bbs.ts.
// This is a real website, NOT a LINE command; no Reply/Push API involved.

// 簡易レート制限用のクライアントキー(IPアドレスをそのまま保存しない = ハッシュ化)
async function clientKeyFor(c: { req: { header: (k: string) => string | undefined } }, scope: string): Promise<string> {
  const ip = c.req.header('CF-Connecting-IP') || c.req.header('x-forwarded-for') || 'unknown'
  const raw = `${scope}:${ip}`
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(raw))
  return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, '0')).join('')
}

app.get('/bbs', async (c) => {
  const category = c.req.query('category') || null
  const validCategory = category && CATEGORIES.some((x) => x.value === category) ? category : null
  const sortParam = c.req.query('sort') || 'new'
  const sort = SORT_OPTIONS.some((s) => s.value === sortParam) ? sortParam : 'new'
  const q = (c.req.query('q') || '').slice(0, 100)
  const page = Math.max(1, parseInt(c.req.query('page') || '1', 10) || 1)

  const [result, stats] = await Promise.all([
    listThreads(c.env, { category: validCategory, sort, q, page }),
    getStats(c.env),
  ])
  return c.html(renderThreadsListPage({ result, activeCategory: validCategory, sort, q, stats }))
})

app.get('/bbs/feed.xml', async (c) => {
  const { threads } = await listThreads(c.env, { sort: 'new', page: 1 })
  return c.text(renderRssFeed(threads), 200, { 'Content-Type': 'application/rss+xml; charset=utf-8' })
})

app.get('/bbs/new', (c) => {
  const category = c.req.query('category') || null
  return c.html(renderNewThreadPage(category))
})

app.post('/bbs/new', async (c) => {
  const key = await clientKeyFor(c, 'new-thread')
  if (await isRateLimited(c.env, key)) {
    return c.html(renderNewThreadPage(null, '投稿間隔が短すぎます。しばらく待ってから再度お試しください。'), 429)
  }

  const body = await c.req.parseBody()
  const category = String(body.category ?? '').trim()
  const title = String(body.title ?? '').trim()
  const content = String(body.content ?? '').trim()
  const author = String(body.author ?? '').trim()

  if (!CATEGORIES.some((x) => x.value === category) || !title || !content || !author) {
    return c.html(renderNewThreadPage(category || null, '入力内容を確認してください。'), 400)
  }

  const id = await createThread(c.env, { category, title, content, author })
  await touchRateLimit(c.env, key)
  return c.redirect(`/bbs/${encodeURIComponent(id)}`)
})

app.get('/bbs/chat', async (c) => {
  const messages = await listChatMessages(c.env)
  return c.html(renderChatPage(messages))
})

app.post('/bbs/chat', async (c) => {
  const key = await clientKeyFor(c, 'chat')
  if (await isRateLimited(c.env, key)) {
    const messages = await listChatMessages(c.env)
    return c.html(renderChatPage(messages), 429)
  }

  const body = await c.req.parseBody()
  const content = String(body.content ?? '').trim()
  const author = String(body.author ?? '').trim()
  if (content && author) {
    await postChatMessage(c.env, content, author)
    await touchRateLimit(c.env, key)
  }
  return c.redirect('/bbs/chat')
})

// 疑似リアルタイム用ポーリングAPI: 指定した created_at より新しいメッセージのみ返す。
// JavaScriptが有効なブラウザから3秒おきに呼ばれる。JSONのみ返し、HTMLは含まない。
app.get('/bbs/chat/messages', async (c) => {
  const after = c.req.query('after') || new Date(0).toISOString()
  const messages = await listChatMessagesAfter(c.env, after)
  return c.json({ messages: messages.map(chatMessageToJson) })
})

// Ajax投稿API: フォームのsubmitをpreventDefaultしてこちらへfetchする。
// 通常の /bbs/chat (フルページPOST) はJavaScript無効時のフォールバックとして残す。
app.post('/bbs/chat/messages', async (c) => {
  const key = await clientKeyFor(c, 'chat')
  if (await isRateLimited(c.env, key)) {
    return c.json({ error: '投稿間隔が短すぎます。少し待ってから再度お試しください。' }, 429)
  }

  const body = await c.req.parseBody()
  const content = String(body.content ?? '').trim()
  const author = String(body.author ?? '').trim()
  if (!content || !author) {
    return c.json({ error: '入力内容を確認してください。' }, 400)
  }

  const message = await postChatMessage(c.env, content, author)
  await touchRateLimit(c.env, key)
  return c.json({ message: chatMessageToJson(message) })
})

// 利用ガイドページ(はじめ方/利用ルール/安全のために/よくある質問/お問い合わせ)。
// お問い合わせフォームは実際にD1へ保存する(フェイクの「受け付けました」表示は禁止)。
// 注意: '/bbs/:id' より前に定義しないと 'guide' がスレッドIDとして誤認識されるため、
// 動的ルートより先に固定パスのガイドルートを登録する。
app.get('/bbs/guide', (c) => {
  return c.html(renderGuidePage())
})

app.post('/bbs/guide/contact', async (c) => {
  const key = await clientKeyFor(c, 'contact')
  const isFetch = c.req.header('X-Requested-With') === 'fetch'
  if (await isRateLimited(c.env, key)) {
    const msg = '送信間隔が短すぎます。しばらく待ってから再度お試しください。'
    if (isFetch) return c.json({ error: msg }, 429)
    return c.html(renderGuidePage({ error: msg }), 429)
  }

  const body = await c.req.parseBody()
  const content = String(body.content ?? '').trim()
  if (!content) {
    const msg = '内容を入力してください。'
    if (isFetch) return c.json({ error: msg }, 400)
    return c.html(renderGuidePage({ error: msg }), 400)
  }

  await saveContactMessage(c.env, content)
  await touchRateLimit(c.env, key)

  if (isFetch) return c.json({ ok: true })
  return c.html(renderGuidePage({ sent: true }))
})

app.get('/bbs/:id', async (c) => {
  const id = c.req.param('id')
  const thread = await getThread(c.env, id)
  if (!thread) return c.html(renderErrorPage(404, 'お探しの投稿は見つかりませんでした'), 404)
  await incrementThreadViews(c.env, id)
  const comments = await listComments(c.env, id)
  return c.html(renderThreadDetailPage(thread, comments))
})

app.post('/bbs/:id/like', async (c) => {
  const id = c.req.param('id')
  const likes = await likeThread(c.env, id)
  if (likes === null) return c.html(renderErrorPage(404, 'お探しの投稿は見つかりませんでした'), 404)
  return c.redirect(`/bbs/${encodeURIComponent(id)}`)
})

app.post('/bbs/:id/comment', async (c) => {
  const id = c.req.param('id')
  const thread = await getThread(c.env, id)
  if (!thread) return c.html(renderErrorPage(404, 'お探しの投稿は見つかりませんでした'), 404)

  const key = await clientKeyFor(c, 'comment')
  if (await isRateLimited(c.env, key)) {
    const comments = await listComments(c.env, id)
    return c.html(renderThreadDetailPage(thread, comments), 429)
  }

  const body = await c.req.parseBody()
  const author = String(body.author ?? '').trim()
  const content = String(body.content ?? '').trim()
  if (author && content) {
    await postComment(c.env, id, author, content)
    await touchRateLimit(c.env, key)
  }
  return c.redirect(`/bbs/${encodeURIComponent(id)}#comments-heading`)
})

// ─── SEO: robots.txt / sitemap.xml ───
app.get('/robots.txt', (c) => {
  return c.text(
    `User-agent: *\nAllow: /\nSitemap: ${SITE_URL}/sitemap.xml\n`,
    200,
    { 'Content-Type': 'text/plain; charset=utf-8' }
  )
})

app.get('/sitemap.xml', async (c) => {
  const threadRows = await listAllThreadIds(c.env)
  const staticUrls = ['/bbs', '/bbs/new', '/bbs/chat', '/bbs/guide', '/gallery']
  const urls = [
    ...staticUrls.map((path) => `<url><loc>${SITE_URL}${path}</loc><changefreq>hourly</changefreq></url>`),
    ...threadRows.map(
      (t) => `<url><loc>${SITE_URL}/bbs/${t.id}</loc><lastmod>${new Date(t.created_at).toISOString()}</lastmod><changefreq>weekly</changefreq></url>`
    ),
  ].join('\n')
  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>`
  return c.text(xml, 200, { 'Content-Type': 'application/xml; charset=utf-8' })
})

// ─── Debug: simulate a text command WITHOUT touching LINE ───
// LINEに実際のメッセージを送らず、Botのコマンドロジックが「何を返そうとしているか」
// だけをJSONで確認できるエンドポイント。テスト用のreplyToken/署名は不要。
// 本番用途ではなく、動作確認専用(データベースへの書き込みは実際に発生する点に注意)。
app.post('/debug/simulate', async (c) => {
  const { text, groupId, userId, pictureUrl } = await c.req.json<{
    text: string
    groupId?: string
    userId?: string
    pictureUrl?: string
  }>()
  if (!text) return c.json({ error: 'text is required' }, 400)

  const ctx = {
    text: text.trim(),
    isGroup: true,
    groupId: groupId ?? 'Cdebug_simulated_group',
    userId: userId ?? 'Udebug_simulated_user',
    displayName: 'デバッグユーザー',
    // Debug-only override so /debug/simulate can exercise the
    // "with avatar" quote-card code path too (e.g. imageGen.ts), not just
    // the no-avatar fallback. Defaults to null exactly as before.
    pictureUrl: pictureUrl ?? null,
    baseUrl: new URL(c.req.url).origin,
  }

  try {
    const directReplies = await routeCommand(c.env, ctx)
    const { messages: queued, ids: queuedIds } = await peekBroadcasts(c.env, ctx.groupId!)
    return c.json({
      input: { text: ctx.text, groupId: ctx.groupId, userId: ctx.userId },
      would_reply_with: [...directReplies, ...queued].slice(0, 5),
      pending_broadcast_queue_ids_not_yet_sent: queuedIds,
      note: 'これはLINEに送信されていません。ロジックが生成した返信内容の確認のみです。',
    })
  } catch (e: any) {
    return c.json({ error: String(e?.message ?? e) }, 500)
  }
})

// ─── LINE Webhook ───
app.post('/webhook', async (c) => {
  const bodyText = await c.req.text()
  const signature = c.req.header('x-line-signature') ?? null

  const valid = await verifySignature(c.env.LINE_CHANNEL_SECRET, bodyText, signature)

  await c.env.DB.prepare(
    `INSERT INTO webhook_debug_logs (timestamp, request_body, has_signature, event_type) VALUES (?, ?, ?, ?)`
  )
    .bind(new Date().toISOString(), bodyText.slice(0, 2000), signature ? 1 : 0, valid ? 'valid' : 'invalid_signature')
    .run()

  if (!valid) return c.json({ error: 'invalid signature' }, 401)

  const payload = JSON.parse(bodyText) as { events: any[] }
  const events = payload.events ?? []

  // IMPORTANT: LINE's webhook connection has a short timeout. We must ACK
  // (return 200) immediately after verifying the signature — NOT after
  // finishing all the DB writes / profile fetches / Reply API calls.
  // Otherwise LINE cancels the connection before we ever call Reply API,
  // which is exactly why real LINE traffic showed up as
  // `outcome: "canceled"` (cpuTime≈4ms, wallTime≈2000ms) in the tail logs
  // while our own sandbox curl requests (which just wait patiently) always
  // succeeded. So: respond first, then keep processing in the background
  // via waitUntil so the replyToken is still fresh when we use it.
  const baseUrl = new URL(c.req.url).origin

  c.executionCtx.waitUntil(
    (async () => {
      for (const event of events) {
        try {
          await handleEvent(c.env, event, baseUrl)
        } catch (e: any) {
          await c.env.DB.prepare(
            `INSERT INTO webhook_debug_logs (timestamp, request_body, has_signature, event_type, error_message) VALUES (?, ?, ?, ?, ?)`
          )
            .bind(new Date().toISOString(), JSON.stringify(event).slice(0, 2000), 1, event.type, String(e?.message ?? e))
            .run()
        }
      }
    })()
  )

  return c.json({ ok: true })
})

async function handleEvent(env: Bindings, event: any, baseUrl: string) {
  switch (event.type) {
    case 'unsend':
      await handleUnsend(env, event)
      return

    case 'message':
      await handleMessageEvent(env, event, baseUrl)
      return

    case 'postback':
      await handlePostback(env, event)
      return

    case 'memberJoined':
      await handleMemberJoined(env, event)
      return

    case 'join':
      if (event.source.type === 'group') {
        const groupId = event.source.groupId
        const summary = await getGroupSummary(env, groupId)
        await ensureGroupMetadata(env, groupId, summary?.groupName ?? null)
      }
      return

    case 'leave':
      // Previously unhandled (fell through to default/no-op): group_metadata
      // never recorded that the bot was removed from a group, so old rows
      // looked identical to currently-joined groups. Record left_at so we
      // can tell "currently joined" apart from "invited once, since removed".
      if (event.source.type === 'group') {
        await markGroupLeft(env, event.source.groupId)
      }
      return

    default:
      return
  }
}

async function handleMemberJoined(env: Bindings, event: any) {
  const groupId = event.source.groupId
  if (!groupId) return
  const joined = event.joined?.members ?? []
  const resolved = await Promise.all(
    joined.map(async (m: any) => {
      const p = await getProfile(env, m.userId, groupId)
      return { userId: m.userId, displayName: p?.displayName }
    })
  )
  const messages = await buildWelcomeMessages(env, groupId, resolved)
  if (messages && event.replyToken) {
    await flushQueueOnReply(env, groupId, event.replyToken, messages)
  }
}

async function handleMessageEvent(env: Bindings, event: any, baseUrl: string) {
  const source = event.source
  const isGroup = source.type === 'group'
  const groupId = source.groupId
  const userId = source.userId
  const replyToken: string | undefined = event.replyToken
  const message = event.message

  let displayName: string | null = null
  let pictureUrl: string | null = null
  if (userId) {
    const profile = await getProfile(env, userId, isGroup ? groupId : undefined)
    displayName = profile?.displayName ?? null
    pictureUrl = profile?.pictureUrl ?? null
  }

  if (isGroup) {
    // Only call the LINE Group Summary API when we don't have a name yet
    // for this group — avoids hitting that endpoint on every single
    // message once group_name is populated.
    const existingMeta = await env.DB.prepare(`SELECT group_name FROM group_metadata WHERE group_id = ?`)
      .bind(groupId)
      .first<{ group_name: string | null }>()
    let groupName = existingMeta?.group_name ?? null
    if (!groupName) {
      const summary = await getGroupSummary(env, groupId)
      groupName = summary?.groupName ?? null
    }
    await ensureGroupMetadata(env, groupId, groupName)
    await touchGroupMember(env, groupId, userId, displayName)

    if (message.type === 'text') {
      await cacheGroupMessage(env, groupId, message.id, userId, displayName, pictureUrl, message.text)
    }

    // Lazily check push-free scheduled-ish features (no cron available).
    await checkAndQueueBirthdays(env, groupId)
    await checkAndQueueGroupFortune(env, groupId)
    await checkAndQueueWeeklyRanking(env, groupId)
    // Any message (not just othello commands or board taps) can be the
    // trigger that notices an abandoned in-progress game and announces its
    // timeout — there's no cron/push to do this proactively.
    await checkAndQueueOthelloTimeout(env, groupId)
  }

  if (message.type !== 'text' || !replyToken) {
    // Still flush any queued broadcasts if we at least have a replyToken.
    if (replyToken && isGroup) await flushQueueOnReply(env, groupId, replyToken, [])
    return
  }

  const text: string = message.text.trim()
  const directReplies = await routeCommand(env, {
    text,
    isGroup,
    groupId,
    userId,
    displayName,
    pictureUrl,
    baseUrl,
    quotedMessageId: message.quotedMessageId,
  })

  if (isGroup) {
    await flushQueueOnReply(env, groupId, replyToken, directReplies)
  } else if (directReplies.length > 0) {
    await replyMessage(env, replyToken, directReplies, userId)
  }
}

// Handles taps on the Othello board (a `postback` action on a legal-move
// cell). Reply-only: the postback event carries its own one-time
// replyToken, exactly like a message event, so this never needs Push API.
async function handlePostback(env: Bindings, event: any) {
  const source = event.source
  if (source.type !== 'group') return
  const groupId = source.groupId
  const userId = source.userId
  const replyToken: string | undefined = event.replyToken
  const data: string = event.postback?.data ?? ''
  if (!groupId || !userId || !replyToken) return

  const othelloMatch = data.match(/^othello:(\d+),(\d+)$/)
  if (othelloMatch) {
    const row = Number(othelloMatch[1])
    const col = Number(othelloMatch[2])
    const profile = await getProfile(env, userId, groupId)
    const result = await applyOthelloMove(env, groupId, userId, row, col, profile?.displayName ?? null)
    // "silent" rejections (same user re-tapping within 5s of their last
    // rejected tap, e.g. "相手の番です。" spam) intentionally send NOTHING —
    // not even to flush the broadcast queue, since a tap isn't a real
    // message and shouldn't be the trigger for unrelated queued notices.
    if (!result.ok && result.silent) return
    const message = result.ok
      ? buildOthelloMessage(result.game, result.note)
      : { type: 'text', text: result.reason }
    await flushQueueOnReply(env, groupId, replyToken, [message])
  }
}

// Combine (a) any direct reply this command produced with (b) whatever is
// sitting in the push-free broadcast queue for this group, then send it all
// in ONE free Reply call (LINE allows up to 5 messages per reply).
//
// IMPORTANT: queued broadcasts are only marked delivered AFTER we confirm
// the reply call actually succeeded. If the reply fails (expired/invalid
// replyToken, network error, etc.) the broadcast rows stay pending and will
// be retried on the next incoming message — nothing is silently lost.
async function flushQueueOnReply(env: Bindings, groupId: string, replyToken: string, direct: LineMessage[]) {
  const { messages: queued, ids: queuedIds } = await peekBroadcasts(env, groupId)
  const combined = [...direct, ...queued].slice(0, 5)
  if (combined.length === 0) return

  const result = await replyMessage(env, replyToken, combined, groupId)
  if (result.ok) {
    await markBroadcastsDelivered(env, queuedIds)
  }
  // If it failed, direct replies are lost (nothing we can do — the
  // replyToken is already spent/invalid either way), but queued broadcasts
  // remain pending and will be included in the next reply attempt.
}

interface CommandCtx {
  text: string
  isGroup: boolean
  groupId?: string
  userId?: string
  displayName: string | null
  pictureUrl: string | null
  baseUrl: string
  quotedMessageId?: string
}

async function routeCommand(env: Bindings, ctx: CommandCtx): Promise<LineMessage[]> {
  const { text } = ctx

  // 固定テストコマンド。今後は言葉を変えず、これだけで動作確認する。
  if (text === 'テスト') {
    return [{ type: 'text', text: `テスト成功 (${new Date().toISOString()})` }]
  }

  if (text === 'ヘルプ' || text.toLowerCase() === 'help') {
    return [{ type: 'text', text: HELP_TEXT }]
  }

  if (text === 'お知らせ') {
    const messages = getLatestAnnouncementMessages(ctx.isGroup ? ctx.groupId ?? null : null)
    if (messages.length === 0) return [{ type: 'text', text: '現在お知らせはありません。' }]
    return messages
  }

  if (text === '運勢' || text === '今日の運勢') {
    if (!ctx.userId) return []
    const sign = await env.DB.prepare(`SELECT zodiac_sign FROM user_zodiac_signs WHERE user_id = ?`)
      .bind(ctx.userId)
      .first<{ zodiac_sign: string }>()
    if (!sign) {
      return [{ type: 'text', text: `星座が未登録です。「星座登録 蟹座」のように送ってください。\n(${ZODIAC_SIGNS.join('/')})` }]
    }
    const f = await getOrCreateDailyFortune(env, todayJst(), sign.zodiac_sign)
    return f ? [{ type: 'text', text: formatFortuneText(f) }] : []
  }

  if (text === '星座登録解除' && ctx.userId) {
    const removed = await unregisterZodiacSign(env, ctx.userId)
    return [{ type: 'text', text: removed ? '星座の登録を解除しました' : '星座は登録されていません' }]
  }

  const zodiacMatch = text.match(/^星座登録\s*(.+)$/)
  if (zodiacMatch && ctx.userId) {
    const sign = zodiacMatch[1].trim()
    if (!ZODIAC_SIGNS.includes(sign)) {
      return [{ type: 'text', text: `不明な星座です。次のいずれかを送ってください:\n${ZODIAC_SIGNS.join('/')}` }]
    }
    await registerZodiacSign(env, ctx.userId, sign)
    return [{ type: 'text', text: `${sign}を登録しました` }]
  }

  const birthdayMatch = text.match(/^誕生日登録\s*(\d{1,2})\/(\d{1,2})$/)
  if (birthdayMatch && ctx.isGroup && ctx.groupId && ctx.userId) {
    const month = parseInt(birthdayMatch[1], 10)
    const day = parseInt(birthdayMatch[2], 10)
    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
      await registerBirthday(env, ctx.groupId, ctx.userId, ctx.displayName ?? '不明', month, day)
      return [{ type: 'text', text: `誕生日を${month}/${day}として登録しました` }]
    }
    return [{ type: 'text', text: '日付の形式が正しくありません。例: 誕生日登録 4/1' }]
  }

  if (text === '誕生日登録解除' && ctx.isGroup && ctx.groupId && ctx.userId) {
    const removed = await unregisterBirthday(env, ctx.groupId, ctx.userId)
    return [{ type: 'text', text: removed ? '誕生日の登録を解除しました' : '誕生日は登録されていません' }]
  }

  if (text === '取り消し通知オフ' && ctx.isGroup && ctx.groupId) {
    await env.DB.prepare(
      `INSERT INTO unsend_restore_settings (group_id, enabled) VALUES (?, 0)
       ON CONFLICT(group_id) DO UPDATE SET enabled = 0, updated_at = CURRENT_TIMESTAMP`
    )
      .bind(ctx.groupId)
      .run()
    return [{ type: 'text', text: '取り消し通知をオフにしました' }]
  }

  if (text === '取り消し通知オン' && ctx.isGroup && ctx.groupId) {
    await env.DB.prepare(
      `INSERT INTO unsend_restore_settings (group_id, enabled) VALUES (?, 1)
       ON CONFLICT(group_id) DO UPDATE SET enabled = 1, updated_at = CURRENT_TIMESTAMP`
    )
      .bind(ctx.groupId)
      .run()
    return [{ type: 'text', text: '取り消し通知をオンにしました' }]
  }

  if (text === 'ウェルカムオフ' && ctx.isGroup && ctx.groupId) {
    await setWelcomeSetting(env, ctx.groupId, false)
    return [{ type: 'text', text: 'ウェルカムメッセージをオフにしました' }]
  }
  if (text === 'ウェルカムオン' && ctx.isGroup && ctx.groupId) {
    await setWelcomeSetting(env, ctx.groupId, true)
    return [{ type: 'text', text: 'ウェルカムメッセージをオンにしました' }]
  }
  const welcomeMsgMatch = text.match(/^ウェルカムメッセージ設定\s*(.+)$/s)
  if (welcomeMsgMatch && ctx.isGroup && ctx.groupId) {
    await setWelcomeSetting(env, ctx.groupId, true, welcomeMsgMatch[1].trim())
    return [{ type: 'text', text: 'ウェルカムメッセージを設定しました' }]
  }
  if (text === 'ウェルカムメッセージ解除' && ctx.isGroup && ctx.groupId) {
    await clearWelcomeMessage(env, ctx.groupId)
    return [{ type: 'text', text: 'カスタムウェルカムメッセージを解除しました(デフォルトの歓迎文に戻ります)' }]
  }

  // Reply mode: bare "めいく" (no colon/text) sent as a LINE reply to someone
  // else's message. quotedMessageId points at the ORIGINAL message, so the
  // card must use ITS author's name/icon and ITS text — not the replier's.
  if (text === 'めいく' && ctx.isGroup && ctx.groupId && ctx.quotedMessageId) {
    const original = await getGroupMessage(env, ctx.groupId, ctx.quotedMessageId)
    if (!original) {
      return [{ type: 'text', text: '元のメッセージが見つかりませんでした(古すぎるか、記録前の発言かもしれません)' }]
    }
    const imageId = await saveQuote(
      env,
      ctx.groupId,
      original.user_id,
      original.display_name ?? '不明',
      original.picture_url,
      original.message_text
    )
    return [buildQuoteImageMessage(ctx.baseUrl, imageId)]
  }

  const quoteMatch = text.match(/^めいく[:：]\s*(.+)$/s)
  if (quoteMatch && ctx.isGroup && ctx.groupId && ctx.userId) {
    const quoteText = quoteMatch[1].trim()
    const imageId = await saveQuote(env, ctx.groupId, ctx.userId, ctx.displayName ?? '不明', ctx.pictureUrl, quoteText)
    return [buildQuoteImageMessage(ctx.baseUrl, imageId)]
  }

  if (text === 'オセロ開始' && ctx.isGroup && ctx.groupId && ctx.userId) {
    const result = await startOthello(env, ctx.groupId, ctx.userId, ctx.displayName)
    if (!result.ok) return [{ type: 'text', text: result.reason }]
    // If starting this game just cleaned up a previous game that had timed
    // out from 5+ minutes of inactivity, mention that before the new board.
    const messages: LineMessage[] = []
    if (result.timeoutMessage) messages.push({ type: 'text', text: result.timeoutMessage })
    messages.push(buildOthelloMessage(result.game))
    return messages
  }

  if (text === 'オセロ参加' && ctx.isGroup && ctx.groupId && ctx.userId) {
    const result = await joinOthello(env, ctx.groupId, ctx.userId, ctx.displayName)
    if (!result.ok) return [{ type: 'text', text: result.reason }]
    return [buildOthelloMessage(result.game)]
  }

  if (text === 'オセロ終了' && ctx.isGroup && ctx.groupId && ctx.userId) {
    const result = await endOthello(env, ctx.groupId, ctx.userId)
    return [{ type: 'text', text: result.ok ? 'オセロを終了しました' : result.reason }]
  }

  if (text === 'オセロ戦績' && ctx.isGroup && ctx.groupId && ctx.userId) {
    const record = await getOthelloRecord(env, ctx.groupId, ctx.userId)
    if (!record) return [{ type: 'text', text: 'まだ対局結果がありません' }]
    return [{ type: 'text', text: `オセロ戦績\n勝ち: ${record.wins}\n負け: ${record.losses}\n引き分け: ${record.draws}` }]
  }

  const tagAddMatch = text.match(/^タグ追加\s*(.+)$/)
  if (tagAddMatch && ctx.isGroup && ctx.groupId) {
    await addTagToGroup(env, ctx.groupId, tagAddMatch[1].trim())
    return [{ type: 'text', text: `タグ「${tagAddMatch[1].trim()}」を追加しました` }]
  }
  const tagRemoveMatch = text.match(/^タグ削除\s*(.+)$/)
  if (tagRemoveMatch && ctx.isGroup && ctx.groupId) {
    await removeTagFromGroup(env, ctx.groupId, tagRemoveMatch[1].trim())
    return [{ type: 'text', text: `タグ「${tagRemoveMatch[1].trim()}」を削除しました` }]
  }
  if (text === 'タグ一覧' && ctx.isGroup && ctx.groupId) {
    const tags = await listGroupTags(env, ctx.groupId)
    return [{ type: 'text', text: tags.length > 0 ? `タグ: ${tags.join('、')}` : 'タグは設定されていません' }]
  }

  if (text === '称号一覧' && ctx.isGroup && ctx.groupId && ctx.userId) {
    const titles = await listUserTitles(env, ctx.userId, ctx.groupId)
    if (titles.length === 0) return [{ type: 'text', text: '所持している称号はありません' }]
    const equipped = await getEquippedTitle(env, ctx.userId, ctx.groupId)
    const lines = titles.map((t) => (t === equipped ? `★${t}（装備中）` : `・${t}`))
    return [{ type: 'text', text: `所持称号一覧\n${lines.join('\n')}` }]
  }

  const equipMatch = text.match(/^称号装備\s*(.+)$/)
  if (equipMatch && ctx.isGroup && ctx.groupId && ctx.userId) {
    const titleName = equipMatch[1].trim()
    const owned = await listUserTitles(env, ctx.userId, ctx.groupId)
    if (!owned.includes(titleName)) {
      return [{ type: 'text', text: `「${titleName}」は所持していません` }]
    }
    await equipTitle(env, ctx.userId, ctx.groupId, titleName)
    return [{ type: 'text', text: `称号「${titleName}」を装備しました` }]
  }

  if (text === '称号確認' && ctx.isGroup && ctx.groupId && ctx.userId) {
    const equipped = await getEquippedTitle(env, ctx.userId, ctx.groupId)
    return [{ type: 'text', text: equipped ? `装備中の称号: ${equipped}` : '称号は装備していません' }]
  }

  return []
}

const HELP_TEXT = `葉っぱもち Bot ヘルプ

【基本】
ヘルプ - このメッセージを表示
お知らせ - 最新のお知らせを確認

【占い】
星座登録 [星座名] - 星座を登録
星座登録解除 - 星座の登録を解除
運勢 - 今日の運勢を確認

【誕生日】
誕生日登録 [月]/[日] - 誕生日を登録(自動でお祝い通知)
誕生日登録解除 - 誕生日の登録を解除

【取り消し通知】
メッセージが削除されると自動で通知(取り消し通知オフ/オンで切替)

【ウェルカム】
ウェルカムオン/オフ - 新メンバー歓迎メッセージの切替
ウェルカムメッセージ設定 [本文] - カスタム歓迎文を設定
ウェルカムメッセージ解除 - カスタム歓迎文を解除してデフォルトに戻す

【名言カード】
めいく:[テキスト] - 名言カードを生成
(他人のメッセージに「返信(リプライ)」で「めいく」だけ送ると、その人の名言カードを生成)

【オセロ】
オセロ開始 - オセロを開始(自分が黒番になる)
オセロ参加 - 白番として参加
オセロ終了 - 対局を終了
オセロ戦績 - 自分の勝敗数を確認
盤面のマスをタップして石を置く

【タグ】
タグ追加/削除/一覧 [タグ名]

【称号】
称号一覧 - 所持している称号を確認
称号装備 [称号名] - 称号を装備
称号確認 - 現在装備中の称号を確認`

export default app
